"""
Broad solar synthesis test: 3000–10000 Å (300–1000 nm).

Compares Python synthesize_jit() against Julia Korg.jl reference across the full
optical+UV range using hydrogen lines only (no metal linelist).

Julia reference generated by: tests/generate_broad_solar_reference.jl
"""

import os
os.environ['JAX_PLATFORMS'] = 'cpu'

import pytest
import numpy as np
import jax.numpy as jnp
from pathlib import Path

REFERENCE_FILE = Path(__file__).parent.parent / "julia_broad_solar_synthesis.h5"
ATM_FILE = Path(__file__).parent / "data" / "sun.mod"


@pytest.fixture(scope="module")
def julia_ref():
    try:
        import h5py
    except ImportError:
        pytest.skip("h5py not installed")
    if not REFERENCE_FILE.exists():
        pytest.skip(
            f"Julia reference not found: {REFERENCE_FILE}. "
            "Run: julia --project=. tests/generate_broad_solar_reference.jl"
        )
    with h5py.File(REFERENCE_FILE, "r") as f:
        return {
            "wavelengths": np.array(f["wavelengths"]),
            "flux": np.array(f["flux"]),
            "continuum": np.array(f["continuum"]),
            "cnorm": np.array(f["continuum_normalized_flux"]),
            "atmosphere": {
                "temperature": np.array(f["atmosphere/temperature"]),
                "electron_number_density": np.array(f["atmosphere/electron_number_density"]),
                "number_density": np.array(f["atmosphere/number_density"]),
                "z": np.array(f["atmosphere/z"]),
                "tau_ref": np.array(f["atmosphere/tau_ref"]),
                "vmic": float(f["atmosphere/vmic"][()]),
            },
            "abundances": np.array(f["abundances"]),
        }


@pytest.fixture(scope="module")
def jit_result(julia_ref):
    if not ATM_FILE.exists():
        pytest.skip(f"Solar atmosphere file not found: {ATM_FILE}")

    from korg.synthesis import (
        precompute_synthesis_data, precompute_atmosphere,
        preprocess_linelist, synthesize_jit,
    )
    from korg.data_loader import (
        ionization_energies, default_partition_funcs,
        default_log_equilibrium_constants,
    )
    from korg.abundances import format_A_X
    from korg.atmosphere import read_model_atmosphere

    atm = read_model_atmosphere(str(ATM_FILE))

    wl_ang = julia_ref["wavelengths"]
    wavelengths_cm = jnp.array(wl_ang * 1e-8)
    vmic_cm_s = julia_ref["atmosphere"]["vmic"] * 1e5

    A_X_log = julia_ref["abundances"]
    abundances = jnp.array(10.0 ** (A_X_log - 12.0))
    abundances = abundances / abundances.sum()

    T_layers = jnp.array(atm.T)
    n_total = jnp.array(atm.n_total)
    ne_layers = jnp.array(atm.ne)
    z_layers = jnp.array(atm.z)
    log_tau_ref = jnp.array(atm.log_tau_ref)

    data = precompute_synthesis_data(
        ionization_energies,
        default_partition_funcs,
        default_log_equilibrium_constants,
    )
    linelist_data = preprocess_linelist([])

    precomp = precompute_atmosphere(
        wavelengths_cm, T_layers, n_total, ne_layers, z_layers,
        log_tau_ref, abundances, vmic_cm_s, data, linelist_data,
    )

    flux, continuum = synthesize_jit(
        wavelengths_cm=wavelengths_cm,
        T_layers=T_layers,
        n_total_layers=n_total,
        ne_layers=ne_layers,
        z_layers=z_layers,
        log_tau_ref=log_tau_ref,
        abundances=abundances,
        vmic_cm_s=vmic_cm_s,
        data=data,
        linelist_data=linelist_data,
        precomputed_atm=precomp,
    )

    cnorm = np.asarray(flux) / np.asarray(continuum)
    return {"flux": np.asarray(flux), "continuum": np.asarray(continuum), "cnorm": cnorm}


def test_broad_solar_continuum_normalized(julia_ref, jit_result):
    """Max |Δcnorm| across 3000–10000 Å must be < 1e-2."""
    py_cnorm = jit_result["cnorm"]
    jl_cnorm = julia_ref["cnorm"]

    abs_diff = np.abs(py_cnorm - jl_cnorm)
    max_diff = float(np.max(abs_diff))
    mean_diff = float(np.mean(abs_diff))
    n_bad = int(np.sum(abs_diff > 1e-2))

    wl = julia_ref["wavelengths"]
    i_worst = int(np.argmax(abs_diff))

    print(f"\nBroad solar synthesis comparison (3000–10000 Å, {len(wl)} pts, H-lines only)")
    print(f"  max |Δcnorm| = {max_diff:.3e}  at {wl[i_worst]:.1f} Å")
    print(f"  mean|Δcnorm| = {mean_diff:.3e}")
    print(f"  pixels > 1e-2: {n_bad}")

    assert max_diff < 1e-2, (
        f"max|Δcnorm| = {max_diff:.3e} exceeds 1e-2 at {wl[i_worst]:.1f} Å"
    )


def test_broad_solar_continuum_flux(julia_ref, jit_result):
    """Continuum flux must agree with Julia to < 1% on average."""
    py_cntm = jit_result["continuum"]
    jl_cntm = julia_ref["continuum"]

    rel_diff = np.abs(py_cntm - jl_cntm) / jl_cntm
    max_rel = float(np.max(rel_diff))
    mean_rel = float(np.mean(rel_diff))

    print(f"\n  Continuum: max rel diff = {max_rel:.3e}, mean = {mean_rel:.3e}")
    assert mean_rel < 0.01, f"mean continuum relative diff {mean_rel:.3e} exceeds 1%"
    assert max_rel < 0.05, f"max continuum relative diff {max_rel:.3e} exceeds 5%"


def test_broad_solar_line_depths_physical(julia_ref, jit_result):
    """Deepest lines (Hα, Hβ, Hγ) must be at least 10% deep in Python result."""
    py_cnorm = jit_result["cnorm"]
    wl = julia_ref["wavelengths"]

    # Coarse 10 Å grid — check nearest point to each Balmer line
    balmer_centers = {"Hα": 6563.0, "Hβ": 4861.0, "Hγ": 4341.0, "Hδ": 4102.0}
    for name, wl0 in balmer_centers.items():
        i = int(np.argmin(np.abs(wl - wl0)))
        # Window ±50 Å to find minimum on coarse grid
        i_lo = max(0, i - 5)
        i_hi = min(len(wl), i + 6)
        depth = 1.0 - float(np.min(py_cnorm[i_lo:i_hi]))
        print(f"  {name} ({wl0:.0f} Å): depth = {depth*100:.1f}%")
        assert depth > 0.10, f"{name} line depth {depth*100:.1f}% is < 10% — H-lines may be missing"
