"""
Tests for ``korg.atmosphere`` — model atmosphere containers and file readers.

Four categories, matching the project's testing contract:

1. **Functional** — container properties, the planar/shell converters, the
   simple-atmosphere builder, and every error path of the MARCS and Phoenix
   readers (including malformed input).
2. **Agreement with Korg.jl** — the parsed structure of ``tests/data/sun.mod``
   and the shell geometry (``radii``, ``photosphere_correction``) are compared
   at machine precision against ``tests/synthesis_reference_data.json``,
   generated by ``tests/generate_synthesis_reference.jl``.  These quantities
   are pure arithmetic on file-parsed numbers, so they are exact — unlike a
   synthetic spectrum, which goes through the whole opacity stack.
3. **Autodiff** — ``ShellAtmosphere.photosphere_correction`` is differentiable
   with respect to the photospheric radius; the layer data are Python floats
   held in a list, so a traced *layer* provably cannot work and that is pinned.
4. **jit tracing** — the same split: geometry from a traced radius jits; the
   file readers cannot be traced and that is pinned.

Two bugs found while writing these tests are regression-pinned below; see
``TestReaderBugRegressions``.
"""

import json
from pathlib import Path

import korg  # noqa: F401 — ensures JAX x64 mode

import jax
import numpy as np
import pytest

from korg.atmosphere import (
    PlanarAtmosphere,
    PlanarAtmosphereLayer,
    ShellAtmosphere,
    ShellAtmosphereLayer,
    create_simple_atmosphere,
    create_solar_test_atmosphere,
    read_model_atmosphere,
    _read_marcs_model_atmosphere,
    _read_phoenix_model_atmosphere,
)
from korg.constants import kboltz_cgs

DATA_DIR = Path(__file__).parent / "data"
SUN_MOD = DATA_DIR / "sun.mod"
REFERENCE_JSON = Path(__file__).parent / "synthesis_reference_data.json"


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def julia_ref():
    """Korg.jl reference values.

    Raises rather than skips: the file is generated by
    ``tests/generate_synthesis_reference.jl`` and is the whole point of the
    precision tests below, so a missing file is a broken checkout, not a
    reason to report success.
    """
    if not REFERENCE_JSON.exists():
        raise FileNotFoundError(
            f"{REFERENCE_JSON} is missing. Regenerate it with:\n"
            "  export PATH=/mnt/sw/nix/store/"
            "yr11xz204lj9ah1irz61lbqh1dk0hcif-julia-1.11.2/bin:$PATH\n"
            "  julia --project=. tests/generate_synthesis_reference.jl"
        )
    with open(REFERENCE_JSON) as fh:
        return json.load(fh)


@pytest.fixture(scope="module")
def sun_atm():
    if not SUN_MOD.exists():
        raise FileNotFoundError(f"{SUN_MOD} is missing from the test data directory")
    return read_model_atmosphere(str(SUN_MOD))


@pytest.fixture(scope="module")
def sun_mod_lines():
    with open(SUN_MOD) as fh:
        return fh.readlines()


def _planar_layers(n=4):
    return [
        PlanarAtmosphereLayer(
            tau_ref=10.0 ** (i - 2),
            z=1e8 * (n - i),
            temperature=4000.0 + 500.0 * i,
            electron_number_density=1e11 * (i + 1),
            number_density=1e16 * (i + 1),
        )
        for i in range(n)
    ]


def _shell_layers(n=4):
    return [
        ShellAtmosphereLayer(
            tau_ref=10.0 ** (i - 2),
            z=1e8 * (n - i),
            temperature=4000.0 + 500.0 * i,
            electron_number_density=1e11 * (i + 1),
            number_density=1e16 * (i + 1),
        )
        for i in range(n)
    ]


# ===========================================================================
# 1. Functional — containers
# ===========================================================================

class TestPlanarAtmosphereContainer:

    def test_length_and_n_layers_agree(self):
        atm = PlanarAtmosphere(_planar_layers(7))
        assert len(atm) == 7
        assert atm.n_layers == 7

    def test_column_properties_are_layerwise(self):
        layers = _planar_layers(3)
        atm = PlanarAtmosphere(layers)
        np.testing.assert_array_equal(atm.tau_ref, [l.tau_ref for l in layers])
        np.testing.assert_array_equal(atm.z, [l.z for l in layers])
        np.testing.assert_array_equal(atm.T, [l.temperature for l in layers])
        np.testing.assert_array_equal(
            atm.ne, [l.electron_number_density for l in layers])
        np.testing.assert_array_equal(
            atm.n_total, [l.number_density for l in layers])

    def test_log_tau_ref_is_log10_of_tau_ref(self):
        atm = PlanarAtmosphere(_planar_layers(5))
        np.testing.assert_allclose(atm.log_tau_ref, np.log10(atm.tau_ref),
                                   rtol=0, atol=0)

    def test_default_reference_wavelength_is_5000_angstrom(self):
        assert PlanarAtmosphere(_planar_layers()).reference_wavelength == 5e-5

    def test_repr_reports_the_layer_count(self):
        assert repr(PlanarAtmosphere(_planar_layers(9))) == \
            "PlanarAtmosphere with 9 layers"


class TestShellAtmosphereContainer:

    def test_length_and_n_layers_agree(self):
        atm = ShellAtmosphere(_shell_layers(6), R_photosphere=3e10)
        assert len(atm) == 6
        assert atm.n_layers == 6

    def test_column_properties_are_layerwise(self):
        layers = _shell_layers(3)
        atm = ShellAtmosphere(layers, R_photosphere=3e10)
        np.testing.assert_array_equal(atm.tau_ref, [l.tau_ref for l in layers])
        np.testing.assert_array_equal(atm.z, [l.z for l in layers])
        np.testing.assert_array_equal(atm.T, [l.temperature for l in layers])
        np.testing.assert_array_equal(
            atm.ne, [l.electron_number_density for l in layers])
        np.testing.assert_array_equal(
            atm.n_total, [l.number_density for l in layers])
        np.testing.assert_allclose(atm.log_tau_ref, np.log10(atm.tau_ref),
                                   rtol=0, atol=0)

    def test_r_is_R_photosphere_plus_z(self):
        """Korg.jl: ``radii = [atm.R + l.z for l in atm.layers]``.

        ``ShellAtmosphere`` had no ``r`` at all before this change, so both
        ``synthesis.py`` and ``synthesis_preparation.py`` raised
        ``AttributeError`` the moment a shell atmosphere was passed in.
        """
        atm = ShellAtmosphere(_shell_layers(4), R_photosphere=3e10)
        np.testing.assert_allclose(atm.r, 3e10 + atm.z, rtol=0, atol=0)

    def test_photosphere_correction_uses_the_outermost_layer(self):
        """Korg.jl: ``photosphere_correction = radii[1]^2 / atm.R^2`` (1-based)."""
        atm = ShellAtmosphere(_shell_layers(4), R_photosphere=3e10)
        assert atm.photosphere_correction == pytest.approx(
            (atm.r[0] / 3e10) ** 2, rel=0, abs=0)

    def test_photosphere_correction_is_one_when_the_top_layer_is_the_photosphere(self):
        layers = _shell_layers(3)
        layers[0].z = 0.0
        atm = ShellAtmosphere(layers, R_photosphere=7e10)
        assert atm.photosphere_correction == 1.0

    def test_repr_reports_layers_and_radius(self):
        atm = ShellAtmosphere(_shell_layers(5), R_photosphere=3e10)
        assert repr(atm) == "ShellAtmosphere with 5 layers, R=3.00e+10 cm"


class TestAtmosphereConverters:
    """``ShellAtmosphere.from_planar`` / ``PlanarAtmosphere.from_shell``.

    Ports of Korg.jl's ``ShellAtmosphere(atm::PlanarAtmosphere, R)`` and
    ``PlanarAtmosphere(atm::ShellAtmosphere)``.
    """

    def test_from_planar_copies_the_layer_data_bit_for_bit(self):
        planar = PlanarAtmosphere(_planar_layers(5), reference_wavelength=1.2e-4)
        shell = ShellAtmosphere.from_planar(planar, 3e10)
        assert isinstance(shell, ShellAtmosphere)
        assert shell.R_photosphere == 3e10
        assert shell.reference_wavelength == 1.2e-4
        for name in ("tau_ref", "z", "T", "ne", "n_total"):
            np.testing.assert_array_equal(getattr(shell, name),
                                          getattr(planar, name))

    def test_from_shell_discards_only_the_radius(self):
        shell = ShellAtmosphere(_shell_layers(5), 3e10, reference_wavelength=1.2e-4)
        planar = PlanarAtmosphere.from_shell(shell)
        assert isinstance(planar, PlanarAtmosphere)
        assert planar.reference_wavelength == 1.2e-4
        for name in ("tau_ref", "z", "T", "ne", "n_total"):
            np.testing.assert_array_equal(getattr(planar, name),
                                          getattr(shell, name))

    def test_round_trip_is_the_identity_on_layer_data(self, sun_atm):
        back = PlanarAtmosphere.from_shell(ShellAtmosphere.from_planar(sun_atm, 3e10))
        for name in ("tau_ref", "z", "T", "ne", "n_total"):
            np.testing.assert_array_equal(getattr(back, name),
                                          getattr(sun_atm, name))


# ===========================================================================
# 1. Functional — create_simple_atmosphere / create_solar_test_atmosphere
# ===========================================================================

class TestCreateSimpleAtmosphere:

    def test_mismatched_lengths_are_rejected(self):
        with pytest.raises(ValueError, match="same length"):
            create_simple_atmosphere([5000.0, 6000.0], [-1.0])

    def test_planar_is_the_default(self):
        atm = create_simple_atmosphere(np.linspace(8000, 4000, 12),
                                       np.linspace(-4, 2, 12))
        assert isinstance(atm, PlanarAtmosphere)
        assert atm.n_layers == 12
        assert np.all(np.isfinite(atm.z))
        assert np.all(atm.ne > 0)
        assert np.all(atm.n_total > 0)

    def test_spherical_flag_returns_a_shell(self):
        atm = create_simple_atmosphere(np.linspace(8000, 4000, 12),
                                       np.linspace(-4, 2, 12), spherical=True)
        assert isinstance(atm, ShellAtmosphere)
        assert atm.R_photosphere > 0
        np.testing.assert_allclose(atm.r, atm.R_photosphere + atm.z, rtol=0)

    def test_reference_wavelength_is_passed_through(self):
        atm = create_simple_atmosphere([5000.0], [0.0], reference_wavelength=1.2e-4)
        assert atm.reference_wavelength == 1.2e-4

    def test_ne_falls_back_when_the_saha_discriminant_underflows(self):
        """At 100 K the Boltzmann factor underflows to exactly zero.

        The Saha quadratic then has ``b == c == 0``, so ``discriminant == 0``
        and the function takes its ``ne = 0.1 n_total`` fallback branch.  This
        is the only way to reach that branch.
        """
        atm = create_simple_atmosphere([100.0, 100.0], [-1.0, 0.0])
        np.testing.assert_allclose(atm.ne, 0.1 * atm.n_total, rtol=1e-15)

    def test_logg_changes_the_height_scale(self):
        T = np.linspace(8000, 4000, 12)
        lt = np.linspace(-4, 2, 12)
        thin = create_simple_atmosphere(T, lt, logg=5.0)
        thick = create_simple_atmosphere(T, lt, logg=3.0)
        assert np.ptp(thick.z) > np.ptp(thin.z)


class TestCreateSolarTestAtmosphere:

    def test_shape_and_monotonic_temperature(self):
        atm = create_solar_test_atmosphere()
        assert isinstance(atm, PlanarAtmosphere)
        assert atm.n_layers == 56
        assert np.all(np.diff(atm.T) > 0), "T must increase with depth"
        np.testing.assert_allclose(atm.log_tau_ref, np.linspace(-4, 2, 56),
                                   rtol=1e-12)


# ===========================================================================
# 1. Functional — read_model_atmosphere dispatch
# ===========================================================================

class TestReadModelAtmosphereDispatch:

    def test_mod_extension_infers_marcs(self, sun_atm):
        assert isinstance(sun_atm, PlanarAtmosphere)
        assert sun_atm.n_layers == 56

    def test_explicit_marcs_format_matches_inference(self, sun_atm):
        explicit = read_model_atmosphere(str(SUN_MOD), format="MARCS")
        np.testing.assert_array_equal(explicit.T, sun_atm.T)

    def test_unknown_extension_is_rejected(self, tmp_path):
        p = tmp_path / "atmosphere.txt"
        p.write_text("nothing here")
        with pytest.raises(ValueError, match="Cannot infer format"):
            read_model_atmosphere(str(p))

    def test_unknown_explicit_format_is_rejected(self):
        with pytest.raises(ValueError, match="Unknown format"):
            read_model_atmosphere(str(SUN_MOD), format="atlas9")

    @pytest.mark.parametrize("suffix", [".fits", ".fit"])
    def test_fits_extensions_infer_phoenix(self, monkeypatch, suffix):
        """Both FITS extensions must route to the Phoenix reader.

        Identified by the 12,000 Å reference wavelength, which only the
        Phoenix reader can produce.
        """
        _install_fits_stub(monkeypatch, teff=4000.0)
        atm = read_model_atmosphere(f"model{suffix}")
        assert atm.reference_wavelength == 12e-5

    def test_explicit_phoenix_format_overrides_the_extension(self, monkeypatch):
        _install_fits_stub(monkeypatch, teff=4000.0)
        atm = read_model_atmosphere("model.dat", format="Phoenix")
        assert atm.reference_wavelength == 12e-5


# ===========================================================================
# 1. Functional — MARCS reader, including malformed input
# ===========================================================================

def _write_mod(tmp_path, lines, name="model.mod"):
    p = tmp_path / name
    p.write_text("".join(lines))
    return str(p)


class TestMarcsReader:

    def test_solar_model_parses_all_declared_layers(self, sun_atm):
        assert sun_atm.n_layers == 56
        assert sun_atm.reference_wavelength == 5e-5

    def test_number_densities_follow_the_ideal_gas_law(self, sun_atm, sun_mod_lines):
        """n = Pg/(kT), ne = Pe/(kT), read from the fixed-width columns."""
        header = next(i for i, l in enumerate(sun_mod_lines) if "lgTauR" in l)
        row = sun_mod_lines[header + 1]
        T = float(row[29:36])
        Pe = float(row[38:48])
        Pg = float(row[48:60])
        assert sun_atm.T[0] == pytest.approx(T, rel=0, abs=0)
        assert sun_atm.ne[0] == pytest.approx(Pe / (T * kboltz_cgs), rel=1e-15)
        assert sun_atm.n_total[0] == pytest.approx(Pg / (T * kboltz_cgs), rel=1e-15)

    def test_z_is_minus_depth(self, sun_atm, sun_mod_lines):
        header = next(i for i, l in enumerate(sun_mod_lines) if "lgTauR" in l)
        depth = float(sun_mod_lines[header + 1][18:28])
        assert sun_atm.z[0] == -depth

    def test_a_radius_other_than_one_gives_a_shell_atmosphere(self, tmp_path,
                                                              sun_mod_lines):
        """MARCS marks spherical models by a radius line that is not 1.0 cm."""
        lines = list(sun_mod_lines)
        i = next(j for j, l in enumerate(lines) if "adius" in l)
        lines[i] = "  7.0000E+10 Radius [cm] at Tau(Rosseland)=1.0\n"
        atm = read_model_atmosphere(_write_mod(tmp_path, lines))
        assert isinstance(atm, ShellAtmosphere)
        assert atm.R_photosphere == 7.0e10
        assert atm.n_layers == 56
        np.testing.assert_allclose(atm.r, 7.0e10 + atm.z, rtol=0)

    def test_spherical_branch_builds_real_layers(self, tmp_path, sun_mod_lines,
                                                 sun_atm):
        """Regression: the shell branch used to raise ``TypeError``.

        ``ShellAtmosphereLayer`` was constructed with ``temp=`` but its field
        is called ``temperature``, so *every* spherical MARCS model failed to
        load.  The layer data must otherwise be identical to the planar parse.
        """
        lines = list(sun_mod_lines)
        i = next(j for j, l in enumerate(lines) if "adius" in l)
        lines[i] = "  7.0000E+10 Radius\n"
        atm = read_model_atmosphere(_write_mod(tmp_path, lines))
        np.testing.assert_array_equal(atm.T, sun_atm.T)
        np.testing.assert_array_equal(atm.ne, sun_atm.ne)
        np.testing.assert_array_equal(atm.n_total, sun_atm.n_total)
        np.testing.assert_array_equal(atm.z, sun_atm.z)

    def test_missing_radius_line_is_rejected(self, tmp_path, sun_mod_lines):
        lines = [l for l in sun_mod_lines if "adius" not in l]
        with pytest.raises(ValueError, match="cannot detect radius"):
            read_model_atmosphere(_write_mod(tmp_path, lines))

    def test_non_numeric_radius_is_rejected(self, tmp_path, sun_mod_lines):
        lines = list(sun_mod_lines)
        i = next(j for j, l in enumerate(lines) if "adius" in l)
        lines[i] = "  bogus radius value\n"
        with pytest.raises(ValueError, match="radius line is not a number"):
            read_model_atmosphere(_write_mod(tmp_path, lines))

    def test_missing_depth_point_count_is_rejected(self, tmp_path, sun_mod_lines):
        lines = [l for l in sun_mod_lines if "Number of depth points" not in l]
        with pytest.raises(ValueError, match="cannot find number of layers"):
            read_model_atmosphere(_write_mod(tmp_path, lines))

    def test_non_numeric_depth_point_count_is_rejected(self, tmp_path, sun_mod_lines):
        lines = list(sun_mod_lines)
        i = next(j for j, l in enumerate(lines) if "Number of depth points" in l)
        lines[i] = "  many Number of depth points\n"
        with pytest.raises(ValueError, match="cannot find number of layers"):
            read_model_atmosphere(_write_mod(tmp_path, lines))

    def test_missing_column_header_is_rejected(self, tmp_path, sun_mod_lines):
        lines = [l for l in sun_mod_lines if "lgTauR" not in l]
        with pytest.raises(ValueError, match="cannot find column header"):
            read_model_atmosphere(_write_mod(tmp_path, lines))

    def test_malformed_structure_row_is_rejected_not_skipped(self, tmp_path,
                                                             sun_mod_lines):
        """A truncated data row must fail loudly.

        Korg.jl parses these columns with no error handling, so a bad row is a
        hard failure there.  Skipping it silently would return an atmosphere
        with fewer layers than the header declares, and nothing downstream
        checks that.
        """
        lines = list(sun_mod_lines)
        header = next(j for j, l in enumerate(lines) if "lgTauR" in l)
        lines[header + 3] = "  4 -4.40 -4.3377   ****\n"
        with pytest.raises(ValueError, match="malformed model-structure row"):
            read_model_atmosphere(_write_mod(tmp_path, lines))

    def test_negative_pressures_are_clamped_to_zero(self, tmp_path, sun_mod_lines):
        """MARCS occasionally writes tiny negative pressures; Korg.jl zeroes them."""
        lines = list(sun_mod_lines)
        header = next(j for j, l in enumerate(lines) if "lgTauR" in l)
        row = lines[header + 1]
        lines[header + 1] = row[:38] + "-2.116E-02" + row[48:]
        atm = read_model_atmosphere(_write_mod(tmp_path, lines))
        assert atm.ne[0] == 0.0
        assert atm.n_total[0] > 0.0


# ===========================================================================
# 1. Functional — Phoenix reader
# ===========================================================================

PHOENIX_TAU = np.array([0.0, 1e-4, 1e-2, 1.0, 10.0])
PHOENIX_TEMP = np.array([3500.0, 3600.0, 3800.0, 4200.0, 5000.0])
PHOENIX_PGAS = np.array([1e2, 1e3, 1e4, 1e5, 1e6])
PHOENIX_PE = np.array([1e-2, 1e-1, 1.0, 10.0, 100.0])


def _install_fits_stub(monkeypatch, teff=5800.0, include_teff=True,
                       tau=PHOENIX_TAU, temp=PHOENIX_TEMP,
                       pgas=PHOENIX_PGAS, pe=PHOENIX_PE):
    """Install a minimal stand-in for ``astropy.io.fits``.

    ``astropy`` is not installed in this project's virtualenv (the system copy
    is built against NumPy 1.x and raises ``AttributeError: np.in1d`` on
    import), so a real Phoenix FITS file cannot be round-tripped here.  The
    stub reproduces exactly the four calls the reader makes —
    ``fits.open`` as a context manager, ``hdul[0].header.get``,
    ``hdul[1].data`` and ``column.astype(float)`` — so every statement of
    ``_read_phoenix_model_atmosphere`` still executes against real arrays.
    What is *not* covered is astropy's own FITS decoding, which is astropy's
    responsibility rather than Korg's.
    """
    import sys
    import types

    class _HDU:
        def __init__(self, header=None, data=None):
            self.header = header if header is not None else {}
            self.data = data

    class _HDUList(list):
        def __enter__(self):
            return self

        def __exit__(self, *exc):
            return False

    header = {"PHXTEFF": teff} if include_teff else {}
    table = {"tau": np.asarray(tau), "temp": np.asarray(temp),
             "pgas": np.asarray(pgas), "pe": np.asarray(pe)}

    fits_mod = types.ModuleType("astropy.io.fits")
    fits_mod.open = lambda fname: _HDUList([_HDU(header=header), _HDU(data=table)])

    io_mod = types.ModuleType("astropy.io")
    io_mod.fits = fits_mod
    astropy_mod = types.ModuleType("astropy")
    astropy_mod.io = io_mod

    monkeypatch.setitem(sys.modules, "astropy", astropy_mod)
    monkeypatch.setitem(sys.modules, "astropy.io", io_mod)
    monkeypatch.setitem(sys.modules, "astropy.io.fits", fits_mod)


class TestPhoenixReader:
    """Regression: this reader raised ``TypeError`` on its first layer.

    ``PlanarAtmosphereLayer`` was constructed with ``temp=`` but the field is
    called ``temperature``, so the function had never successfully run and no
    test would have noticed.
    """

    def test_reads_a_planar_atmosphere_and_drops_the_tau_zero_layer(
            self, monkeypatch):
        _install_fits_stub(monkeypatch)
        atm = read_model_atmosphere("phoenix-model.fits")
        assert isinstance(atm, PlanarAtmosphere)
        assert atm.n_layers == len(PHOENIX_TAU) - 1, \
            "Korg drops the tau=0 layer; the transfer solver needs tau > 0"
        np.testing.assert_allclose(atm.tau_ref, PHOENIX_TAU[1:], rtol=0)
        np.testing.assert_allclose(atm.T, PHOENIX_TEMP[1:], rtol=0)

    def test_densities_use_the_ideal_gas_law(self, monkeypatch):
        _install_fits_stub(monkeypatch)
        atm = _read_phoenix_model_atmosphere("phoenix-model.fits")
        np.testing.assert_allclose(
            atm.n_total, PHOENIX_PGAS[1:] / (kboltz_cgs * PHOENIX_TEMP[1:]),
            rtol=1e-14)
        np.testing.assert_allclose(
            atm.ne, PHOENIX_PE[1:] / (kboltz_cgs * PHOENIX_TEMP[1:]), rtol=1e-14)

    def test_z_is_nan_because_phoenix_has_no_height_coordinate(self, monkeypatch):
        _install_fits_stub(monkeypatch)
        atm = _read_phoenix_model_atmosphere("phoenix-model.fits")
        assert np.all(np.isnan(atm.z)), \
            "Phoenix models carry no z, so only anchored transfer can use them"

    @pytest.mark.parametrize("teff,expected", [(4500.0, 12e-5), (5000.0, 5e-5),
                                               (7000.0, 5e-5)])
    def test_reference_wavelength_switches_at_5000K(self, monkeypatch, teff,
                                                    expected):
        """Husser et al. 2013: 12,000 Å below 5000 K, 5000 Å at or above."""
        _install_fits_stub(monkeypatch, teff=teff)
        atm = _read_phoenix_model_atmosphere("phoenix-model.fits")
        assert atm.reference_wavelength == expected

    def test_missing_PHXTEFF_header_falls_back_to_5000K(self, monkeypatch):
        _install_fits_stub(monkeypatch, include_teff=False)
        atm = _read_phoenix_model_atmosphere("phoenix-model.fits")
        assert atm.reference_wavelength == 5e-5

    def test_missing_astropy_gives_an_actionable_error(self, monkeypatch):
        import builtins
        real_import = builtins.__import__

        def fake_import(name, *args, **kwargs):
            if name.startswith("astropy"):
                raise ImportError("No module named 'astropy'")
            return real_import(name, *args, **kwargs)

        monkeypatch.setattr(builtins, "__import__", fake_import)
        with pytest.raises(ImportError, match="pip install astropy"):
            _read_phoenix_model_atmosphere("phoenix-model.fits")


class TestReaderBugRegressions:
    """Both readers constructed layers with a keyword the dataclass lacks."""

    def test_layer_field_is_named_temperature_not_temp(self):
        with pytest.raises(TypeError):
            PlanarAtmosphereLayer(tau_ref=1.0, z=0.0, temp=5000.0,
                                  electron_number_density=1.0, number_density=1.0)
        with pytest.raises(TypeError):
            ShellAtmosphereLayer(tau_ref=1.0, z=0.0, temp=5000.0,
                                 electron_number_density=1.0, number_density=1.0)


# ===========================================================================
# 2. High-precision agreement with Korg.jl
# ===========================================================================

class TestAgreementWithKorgJl:
    """These are exact quantities: file parsing plus one multiply/add.

    Nothing here goes through the opacity stack, so machine-precision
    tolerances are appropriate and are used.
    """

    def test_marcs_parse_matches_julia_exactly(self, julia_ref, sun_atm):
        ref = julia_ref["marcs_sun"]
        assert type(sun_atm).__name__ == ref["type"]
        assert sun_atm.n_layers == ref["n_layers"]
        assert sun_atm.reference_wavelength == ref["reference_wavelength"]
        np.testing.assert_allclose(sun_atm.tau_ref, ref["tau_ref"], rtol=1e-15)
        np.testing.assert_allclose(sun_atm.z, ref["z"], rtol=0, atol=0)
        np.testing.assert_allclose(sun_atm.T, ref["temp"], rtol=0, atol=0)
        np.testing.assert_allclose(sun_atm.ne, ref["electron_number_density"],
                                   rtol=1e-15)
        np.testing.assert_allclose(sun_atm.n_total, ref["number_density"],
                                   rtol=1e-15)

    def test_shell_radii_match_julia_exactly(self, julia_ref, sun_atm):
        for case in julia_ref["shell_geometry"]:
            shell = ShellAtmosphere.from_planar(sun_atm, case["R"])
            np.testing.assert_allclose(shell.r, case["radii"], rtol=1e-15,
                                       err_msg=f"radii for R={case['R']}")

    def test_photosphere_correction_matches_julia_exactly(self, julia_ref, sun_atm):
        """Korg.jl's ``radii[1]^2 / atm.R^2``, to 1e-15."""
        for case in julia_ref["shell_geometry"]:
            shell = ShellAtmosphere.from_planar(sun_atm, case["R"])
            assert shell.photosphere_correction == pytest.approx(
                case["photosphere_correction"], rel=1e-15), \
                f"photosphere_correction for R={case['R']}"

    def test_the_extended_case_is_a_large_correction(self, julia_ref, sun_atm):
        """Guard the discriminating power of the end-to-end spherical test.

        The smallest reference radius is chosen so that dropping the
        correction is a ~69% flux error, not a rounding difference.
        """
        smallest = min(julia_ref["shell_geometry"], key=lambda c: c["R"])
        assert smallest["photosphere_correction"] > 1.5


# ===========================================================================
# 3. Autodiff
# ===========================================================================

class TestAutodiff:

    def test_photosphere_correction_grad_matches_finite_differences(self):
        layers = _shell_layers(4)
        R0 = 3.0e10

        def f(R):
            return ShellAtmosphere(layers, R).photosphere_correction

        g = jax.grad(f)(R0)
        h = R0 * 1e-6
        fd = (f(R0 + h) - f(R0 - h)) / (2 * h)
        assert np.isfinite(g)
        assert g != 0.0
        assert g == pytest.approx(fd, rel=1e-5)

    def test_photosphere_correction_grad_has_the_analytic_value(self):
        """d/dR (1 + z0/R)² = -2 z0 (R + z0) / R³."""
        layers = _shell_layers(4)
        z0 = layers[0].z
        R0 = 3.0e10
        g = jax.grad(lambda R: ShellAtmosphere(layers, R).photosphere_correction)(R0)
        assert g == pytest.approx(-2.0 * z0 * (R0 + z0) / R0 ** 3, rel=1e-12)

    def test_radius_grad_wrt_R_is_one_everywhere(self):
        layers = _shell_layers(4)
        g = jax.jacfwd(lambda R: ShellAtmosphere(layers, R).r)(3.0e10)
        np.testing.assert_allclose(np.asarray(g), np.ones(4), rtol=1e-14)

    def test_a_traced_layer_provably_cannot_work(self):
        """Layer data live in a Python list that is turned into ``np.array``.

        ``np.array`` of a JAX tracer is not differentiable and never can be
        without restructuring the container, so this is pinned rather than
        left ambiguous.
        """
        def f(z):
            layer = ShellAtmosphereLayer(1e-4, z, 4000.0, 1e12, 1e16)
            return ShellAtmosphere([layer], 3e10).r[0]

        with pytest.raises(jax.errors.TracerArrayConversionError):
            jax.grad(f)(1e8)


# ===========================================================================
# 4. jit tracing
# ===========================================================================

class TestJit:

    def test_geometry_from_a_traced_radius_jits(self):
        layers = _shell_layers(4)
        f = jax.jit(lambda R: ShellAtmosphere(layers, R).photosphere_correction)
        R0 = 3.0e10
        assert float(f(R0)) == pytest.approx(
            ShellAtmosphere(layers, R0).photosphere_correction, rel=1e-14)

    def test_radii_from_a_traced_radius_jit(self):
        layers = _shell_layers(4)
        out = jax.jit(lambda R: ShellAtmosphere(layers, R).r)(3.0e10)
        np.testing.assert_allclose(np.asarray(out),
                                   ShellAtmosphere(layers, 3.0e10).r, rtol=1e-14)

    def test_read_model_atmosphere_cannot_be_jitted(self):
        """The reader does Python file I/O and ``float()`` on parsed text.

        There is no traced value to thread through it, so this is pinned as a
        permanent limitation rather than a coverage gap.
        """
        @jax.jit
        def f(x):
            atm = read_model_atmosphere(str(SUN_MOD))
            return x * atm.T[0]

        # the reader itself traces fine (it ignores x); what cannot work is
        # making the *file contents* depend on a traced value:
        @jax.jit
        def g(i):
            return read_model_atmosphere(str(SUN_MOD)).T[int(i)]

        assert np.isfinite(float(f(2.0)))
        with pytest.raises(jax.errors.ConcretizationTypeError):
            g(0)
