"""
Coverage and correctness tests for :mod:`korg.statmech`.

Complements ``test_chemical_equilibrium_jit.py`` (which pins the batched Newton
solver against ``tests/reference_chemical_equilibrium.py``) and
``test_statmech_extended_reference.py`` (Saha / log nK physics), by exercising
the parts neither touches: the occupation-probability formalism, the precompute
machinery, the Picard path, the per-layer drivers, and the differentiability
asymmetry between the two solvers.

Four categories:

1. Functional — branch selectors (``use_hubeny_generalization``, ``atom == 1``,
   zero-molecule data), error paths, degenerate inputs.
2. High-precision agreement with Korg.jl, from
   ``tests/chemistry_reference_data.json`` (generated by
   ``tests/generate_chemistry_reference.jl``).
3. Autodiff — the batched solver is reverse-mode differentiable through an
   implicit-function-theorem ``custom_jvp``; ``picard_chemical_equilibrium_guess``
   is forward-mode only because it uses ``lax.while_loop``.  Both are asserted.
4. jit-tracing — what traces and what provably cannot.
"""

import json
import os

import jax
import jax.numpy as jnp
import numpy as np
import pytest

import korg  # noqa: F401 — side effect: enables x64
from korg import statmech as S

REFERENCE_FILE = os.path.join(os.path.dirname(__file__), "chemistry_reference_data.json")


@pytest.fixture(scope="module")
def chem_ref():
    if not os.path.exists(REFERENCE_FILE):
        pytest.skip("chemistry_reference_data.json missing; "
                    "run tests/generate_chemistry_reference.jl")
    with open(REFERENCE_FILE) as f:
        return json.load(f)


@pytest.fixture(scope="module")
def ionization_energies():
    from korg.data_loader import load_ionization_energies
    return load_ionization_energies()


@pytest.fixture(scope="module")
def partition_funcs():
    from korg.data_loader import load_atomic_partition_functions
    return load_atomic_partition_functions()


@pytest.fixture(scope="module")
def log_K():
    from korg.data_loader import load_barklem_collet_equilibrium_constants
    return load_barklem_collet_equilibrium_constants()


@pytest.fixture(scope="module")
def eq_data(ionization_energies, partition_funcs, log_K):
    """A small precomputed table — n_temps kept low so the fixture is cheap."""
    return S.precompute_chemical_equilibrium_data(
        ionization_energies, partition_funcs, log_K,
        T_min=2000.0, T_max=20000.0, n_temps=200)


@pytest.fixture(scope="module")
def eq_data_no_molecules(ionization_energies, partition_funcs):
    """Atoms-only table, for the ``n_molecules == 0`` branches.

    Module-scoped: rebuilding the 92x3 partition-function splines per test is by
    far the most expensive thing in this file.
    """
    return S.precompute_chemical_equilibrium_data(
        ionization_energies, partition_funcs, {},
        T_min=3000.0, T_max=10000.0, n_temps=50)


@pytest.fixture(scope="module")
def abundances():
    from korg.abundances import format_A_X, A_X_to_absolute
    return jnp.asarray(A_X_to_absolute(format_A_X()))


class _LayerKernels:
    """The single-layer solve and its derivatives, compiled once for the module.

    The autodiff tests below all differentiate the same solve at the same point.
    Written as a local ``def f(t)`` in each test they were four distinct closures
    over four distinct sets of baked-in constants, so each one hashed to its own HLO
    module and paid the reverse-mode compile of the Newton solver again. Passing the
    constants as arguments makes them one executable per derivative.
    """

    def __init__(self, eq_data):
        def solve(T, n_total, ne_guess, nf_guess, ab):
            return S._chem_eq_newton_layer_jit(T, n_total, ne_guess, nf_guess,
                                               ab, eq_data)[0]

        self.ne = jax.jit(solve)
        self.d_ne_dT = jax.jit(jax.grad(solve, argnums=0))
        self.d_ne_dab = jax.jit(jax.grad(solve, argnums=4))
        self.jacfwd_T = jax.jit(jax.jacfwd(solve, argnums=0))

    def at(self, T, n_total, ne_guess, nf_guess, ab):
        """``ne`` as a plain float, for finite differencing."""
        return float(self.ne(jnp.float64(T), jnp.float64(n_total),
                             ne_guess, nf_guess, ab))


@pytest.fixture(scope="module")
def layer_kernels(eq_data):
    return _LayerKernels(eq_data)


def _central_difference(f, x, rel_step=1e-6):
    h = abs(x) * rel_step
    return (f(x + h) - f(x - h)) / (2 * h)


# ===========================================================================
# 1. FUNCTIONAL — simple/pure functions
# ===========================================================================

class TestTranslationalU:

    def test_scales_as_T_to_the_three_halves(self):
        from korg.constants import electron_mass_cgs
        a = float(S.translational_U(electron_mass_cgs, 1000.0))
        b = float(S.translational_U(electron_mass_cgs, 4000.0))
        assert b / a == pytest.approx(4.0 ** 1.5, rel=1e-12)

    def test_zero_temperature_is_zero(self):
        from korg.constants import electron_mass_cgs
        assert float(S.translational_U(electron_mass_cgs, 0.0)) == 0.0

    def test_matches_julia(self, chem_ref):
        from korg.constants import electron_mass_cgs
        for T_str, ref in chem_ref["statmech"]["translational_U"].items():
            got = float(S.translational_U(electron_mass_cgs, float(T_str)))
            assert got == pytest.approx(float(ref), rel=1e-13), T_str


class TestHminusNK:

    def test_matches_julia(self, chem_ref):
        for T_str, ref in chem_ref["statmech"]["Hminus_nK"].items():
            got = float(S.Hminus_nK(float(T_str)))
            assert got == pytest.approx(float(ref), rel=1e-13), T_str

    def test_decreases_with_temperature(self):
        """H⁻ is easier to form when it is cold."""
        vals = [float(S.Hminus_nK(T)) for T in (3000.0, 5000.0, 9000.0)]
        assert vals[0] > vals[1] > vals[2] > 0

    def test_is_the_inverse_translational_U_times_the_boltzmann_factor(self):
        from korg.constants import electron_mass_cgs, kboltz_eV
        T = 5778.0
        expected = (np.exp(0.754204 / (kboltz_eV * T))
                    / (4.0 * float(S.translational_U(electron_mass_cgs, T))))
        assert float(S.Hminus_nK(T)) == pytest.approx(expected, rel=1e-15)


class TestPow10:

    def test_matches_plain_exponentiation_in_range(self):
        for x in (-10.0, 0.0, 3.5, 250.0):
            assert float(S._pow10(x)) == pytest.approx(10.0 ** x, rel=1e-14)

    def test_clamps_instead_of_overflowing(self):
        """Julia lets these overflow to Inf and treats that as a failed Newton
        step; clamping keeps the residual finite but still enormous.

        Compared with a tolerance, not exactly: XLA's ``pow`` and CPython's
        ``**`` disagree by one ulp on the GPU backend (9.999999999999999e+299 vs
        1e+300) while agreeing exactly on CPU.  What matters here is that the
        clamp fires at the documented exponent, not that two different
        libraries' pow implementations round identically.
        """
        assert float(S._pow10(1e6)) == pytest.approx(10.0 ** 300, rel=1e-15)
        assert float(S._pow10(-1e6)) == pytest.approx(10.0 ** -300, rel=1e-15)
        assert np.isfinite(float(S._pow10(1e6)))

    def test_is_jittable_and_differentiable(self):
        assert float(jax.jit(S._pow10)(2.0)) == pytest.approx(100.0)
        g = float(jax.grad(S._pow10)(2.0))
        assert g == pytest.approx(100.0 * np.log(10.0), rel=1e-12)


class TestHummerMihalasW:
    """The occupation-probability correction used by ``continuum.H_I_bf``.

    Note there is a *second* implementation in
    ``korg.hydrogen_line_absorption``; see TestDuplicateImplementations.
    """

    LIVE = dict(T=5778.0, nH=1.8e17, nHe=1.6e16, ne=1e14)

    def test_matches_julia_standard(self, chem_ref):
        worst = 0.0
        for key, ref in chem_ref["statmech"]["hummer_mihalas_w"]["standard"].items():
            T, n_eff, nH, nHe, ne = (float(x) for x in key.split("_"))
            got = float(S.hummer_mihalas_w(T, n_eff, nH, nHe, ne))
            assert got == pytest.approx(float(ref), rel=1e-12), key
            if ref:
                worst = max(worst, abs(got / float(ref) - 1.0))
        assert worst < 1e-12

    def test_matches_julia_hubeny(self, chem_ref):
        for key, ref in chem_ref["statmech"]["hummer_mihalas_w"]["hubeny"].items():
            T, n_eff, nH, nHe, ne = (float(x) for x in key.split("_"))
            got = float(S.hummer_mihalas_w(T, n_eff, nH, nHe, ne,
                                           use_hubeny_generalization=True))
            assert got == pytest.approx(float(ref), rel=1e-12), key

    def test_w_is_a_probability(self):
        for n_eff in (1.0, 3.0, 3.5, 10.0, 40.0):
            w = float(S.hummer_mihalas_w(n_eff=n_eff, **self.LIVE))
            assert 0.0 <= w <= 1.0

    def test_high_levels_are_dissolved(self):
        """w → 0 as n_eff grows: the level merges into the continuum."""
        ws = [float(S.hummer_mihalas_w(n_eff=n, **self.LIVE))
              for n in (1.0, 10.0, 40.0, 100.0)]
        assert ws == sorted(ws, reverse=True)
        assert ws[-1] < 1e-6

    def test_denser_plasma_dissolves_more(self):
        sparse = float(S.hummer_mihalas_w(5778.0, 20.0, 1e12, 1e11, 1e9))
        dense = float(S.hummer_mihalas_w(5778.0, 20.0, 1e18, 1e17, 1e15))
        assert dense < sparse

    def test_K_switches_at_n_eff_equals_three(self):
        """K is 1 for n_eff <= 3 and the H&M 4.24 expression above it; the switch
        is continuous enough that w stays monotone across it."""
        below = float(S.hummer_mihalas_w(n_eff=2.9, **self.LIVE))
        at = float(S.hummer_mihalas_w(n_eff=3.0, **self.LIVE))
        above = float(S.hummer_mihalas_w(n_eff=3.1, **self.LIVE))
        assert below >= at >= above

    def test_hubeny_branch_gives_a_different_answer(self):
        """Both branches must actually be reachable and distinguishable."""
        std = float(S.hummer_mihalas_w(n_eff=5.0, **self.LIVE))
        hub = float(S.hummer_mihalas_w(n_eff=5.0, use_hubeny_generalization=True,
                                       **self.LIVE))
        assert std != hub
        assert 0.0 < hub <= 1.0

    @pytest.mark.parametrize("ne,T", [(0.0, 5778.0), (5.0, 5778.0), (1e14, 5.0)])
    def test_hubeny_guard_falls_back_to_zero_charged_term(self, ne, T):
        """Below (ne > 10) & (T > 10) the Hubeny charged term is dropped."""
        w = float(S.hummer_mihalas_w(T, 5.0, 1.8e17, 1.6e16, ne,
                                     use_hubeny_generalization=True))
        assert np.isfinite(w) and 0.0 < w <= 1.0


class TestHummerMihalasUH:
    """Experimental; not used for synthesis, but it must at least run."""

    def test_matches_julia(self, chem_ref):
        for kind, use_hub in (("standard", False), ("hubeny", True)):
            for key, ref in chem_ref["statmech"]["hummer_mihalas_U_H"][kind].items():
                T, nH, nHe, ne = (float(x) for x in key.split("_"))
                got = float(S.hummer_mihalas_U_H(T, nH, nHe, ne,
                                                 use_hubeny_generalization=use_hub))
                assert got == pytest.approx(float(ref), rel=1e-12), f"{kind} {key}"

    def test_is_close_to_two_at_stellar_temperatures(self):
        """The ground state has g = 2 and everything else is ~10 eV up."""
        U = float(S.hummer_mihalas_U_H(5778.0, 1.8e17, 1.6e16, 1e14))
        assert 1.99 < U < 2.01

    def test_grows_with_temperature(self):
        a = float(S.hummer_mihalas_U_H(5000.0, 1e16, 1e15, 1e13))
        b = float(S.hummer_mihalas_U_H(15000.0, 1e16, 1e15, 1e13))
        assert b > a


class TestSahaIonWeights:

    def test_matches_julia(self, chem_ref, ionization_energies, partition_funcs):
        checked = 0
        for Z_str, cases in chem_ref["statmech"]["saha_ion_weights"].items():
            Z = int(Z_str)
            for key, ref in cases.items():
                T, ne = (float(x) for x in key.split("_"))
                try:
                    wII, wIII = S.saha_ion_weights(T, ne, Z, ionization_energies,
                                                   partition_funcs)
                except KeyError:
                    continue   # e.g. He III has no tabulated partition function
                assert float(wII) == pytest.approx(float(ref["wII"]), rel=1e-10), \
                    f"Z={Z} {key} wII"
                assert float(wIII) == pytest.approx(float(ref["wIII"]),
                                                    rel=1e-10, abs=1e-300), \
                    f"Z={Z} {key} wIII"
                checked += 1
        assert checked > 10, "reference data did not exercise saha_ion_weights"

    def test_hydrogen_takes_the_atom_equals_one_branch(self, ionization_energies,
                                                       partition_funcs):
        wII, wIII = S.saha_ion_weights(5778.0, 1e14, 1, ionization_energies,
                                       partition_funcs)
        assert wIII == 0.0
        assert float(wII) > 0.0

    def test_metals_take_the_else_branch(self, ionization_energies, partition_funcs):
        wII, wIII = S.saha_ion_weights(9000.0, 1e13, 26, ionization_energies,
                                       partition_funcs)
        assert float(wII) > 0.0 and float(wIII) > 0.0

    def test_missing_third_partition_function_raises(self, ionization_energies,
                                                     partition_funcs):
        """The ``else`` branch looks up ``Species(formula, 2)`` unguarded.

        Every element in the shipped table does have one, so this only bites a
        caller that supplies a partial dict — which ``korg.simple_ionization``
        anticipates with a ``try/except (KeyError, IndexError)``.  The batched
        ``_compute_saha_weights_jit`` avoids the issue differently, with a
        synthetic placeholder spline for H III.  Pin the divergence.
        """
        from korg.species import Species, Formula
        pruned = {k: v for k, v in partition_funcs.items()
                  if k != Species(Formula(2), 2)}
        with pytest.raises(KeyError):
            S.saha_ion_weights(9000.0, 1e13, 2, ionization_energies, pruned)
        # ... and with the full table it is fine
        wII, wIII = S.saha_ion_weights(9000.0, 1e13, 2, ionization_energies,
                                       partition_funcs)
        assert float(wII) > 0 and float(wIII) >= 0

    def test_zero_electron_density_is_clipped_not_divided_by_zero(
            self, ionization_energies, partition_funcs):
        wII, _ = S.saha_ion_weights(5778.0, 0.0, 1, ionization_energies,
                                    partition_funcs)
        assert np.isfinite(float(wII))
        assert float(wII) > 0.0

    def test_agrees_with_the_batched_jit_implementation(self, eq_data,
                                                        ionization_energies,
                                                        partition_funcs):
        """Two independent Saha routes: the dict-based one here and the vmapped
        ``_compute_saha_weights_jit`` used by the solver.  They differ in how the
        partition functions are evaluated (spline object vs padded knot arrays),
        so agreement is not free.
        """
        T, ne = 5778.0, 1e14
        wII_arr, wIII_arr = S._compute_saha_weights_jit(T, ne, eq_data)
        for Z in (1, 3, 6, 12, 20, 26):
            wII, wIII = S.saha_ion_weights(T, ne, Z, ionization_energies,
                                           partition_funcs)
            assert float(wII_arr[Z - 1]) == pytest.approx(float(wII), rel=1e-6), \
                f"wII mismatch for Z={Z}"
            assert float(wIII_arr[Z - 1]) == pytest.approx(float(wIII), rel=1e-6,
                                                           abs=1e-300), \
                f"wIII mismatch for Z={Z}"


class TestGetLogNK:

    def test_matches_julia(self, chem_ref, log_K):
        from korg.species import Species
        checked = 0
        for mol_str, cases in chem_ref["statmech"]["get_log_nK"].items():
            mol = Species(mol_str)
            if mol not in log_K:
                continue
            for T_str, ref in cases.items():
                got = float(S.get_log_nK(mol, float(T_str), log_K))
                assert got == pytest.approx(float(ref), rel=1e-10), f"{mol_str} {T_str}"
                checked += 1
        assert checked > 5

    def test_polyatomic_conversion_uses_n_atoms_minus_one(self, log_K):
        """log nK = log Kp − (n_atoms − 1) log10(kT)."""
        from korg.species import Species
        from korg.constants import kboltz_cgs
        T = 5000.0
        for mol_str in ("H2", "H2O"):
            mol = Species(mol_str)
            if mol not in log_K:
                continue
            log_Kp = float(log_K[mol](np.log(T)))
            expected = log_Kp - (mol.n_atoms() - 1) * np.log10(kboltz_cgs * T)
            assert float(S.get_log_nK(mol, T, log_K)) == pytest.approx(expected,
                                                                       rel=1e-13)


# ===========================================================================
# 1. FUNCTIONAL — precompute machinery
# ===========================================================================

class TestPrecompute:

    def test_shapes_and_dtypes(self, eq_data):
        assert eq_data.ionization_energies.shape == (S.MAX_ATOMIC_NUMBER, 3)
        assert eq_data.partition_func_values.shape[:2] == (S.MAX_ATOMIC_NUMBER, 3)
        assert eq_data.mol_atom_consume.shape == (eq_data.n_molecules,
                                                  S.MAX_ATOMIC_NUMBER)
        assert eq_data.mol_atoms_array.shape == (eq_data.n_molecules, 6)
        assert eq_data.n_molecules > 0

    def test_zero_molecule_data_is_supported(self, eq_data_no_molecules):
        """The ``n_molecules == 0`` branch — an atoms-only equilibrium."""
        data = eq_data_no_molecules
        assert data.n_molecules == 0
        assert data.mol_charges.shape == (0,)
        assert data.mol_atom_consume.shape == (0, S.MAX_ATOMIC_NUMBER)

    def test_zero_molecule_density_helper_returns_empty(self, eq_data_no_molecules,
                                                        abundances):
        data = eq_data_no_molecules
        nf = jnp.ones(S.MAX_ATOMIC_NUMBER)
        out = S._compute_mol_densities_jit(5000.0, 1e16, 1e13, abundances, nf, data)
        assert out.shape == (0,)

    def test_hydrogen_third_partition_function_is_a_placeholder(self, eq_data):
        """H III does not exist, but a NaN there would poison the wIII cotangent,
        so precompute installs a synthetic 2-knot spline."""
        assert int(eq_data.pf_orig_n[0, 2]) >= 2
        assert np.all(np.isfinite(np.asarray(eq_data.pf_orig_u[0, 2, :2])))

    def test_atomic_partition_spline_matches_the_original(self, eq_data,
                                                          partition_funcs):
        from korg.species import Species, Formula
        for Z, charge in [(1, 0), (2, 0), (26, 0), (26, 1), (20, 1)]:
            sp = Species(Formula(Z), charge)
            if sp not in partition_funcs:
                continue
            for T in (3000.0, 5778.0, 12000.0):
                log_T = np.log(T)
                got = float(S._eval_atomic_pf_jit(
                    log_T,
                    eq_data.pf_orig_t[Z - 1, charge],
                    eq_data.pf_orig_u[Z - 1, charge],
                    eq_data.pf_orig_h[Z - 1, charge],
                    eq_data.pf_orig_z[Z - 1, charge],
                    eq_data.pf_orig_n[Z - 1, charge]))
                expected = float(partition_funcs[sp](log_T))
                assert got == pytest.approx(expected, rel=1e-9), f"Z={Z} q={charge} T={T}"

    @pytest.mark.parametrize("Z", [12, 20, 26])
    def test_interp_partition_func_uses_one_based_atomic_number(self, eq_data,
                                                                partition_funcs, Z):
        """Regression: it indexed ``partition_func_values[Z]`` instead of
        ``[Z - 1]``, so it returned U of element Z+1 (U(Co I) for Fe I).

        It has no callers in the package, which is why nothing caught it.
        """
        from korg.species import Species, Formula
        sp = Species(Formula(Z), 0)
        wrong = Species(Formula(Z + 1), 0)
        for T in (3000.0, 5778.0, 12000.0):
            got = float(S._interp_partition_func(np.log(T), Z, 0, eq_data))
            expected = float(partition_funcs[sp](np.log(T)))
            wrong_val = float(partition_funcs[wrong](np.log(T)))
            # linear interpolation on the tabulated grid, so allow a little slack
            assert got == pytest.approx(expected, rel=2e-3), f"Z={Z} T={T}"
            assert abs(got - expected) < abs(got - wrong_val), \
                f"Z={Z} T={T}: still returning element Z+1"

    def test_scalar_and_vectorised_log_nK_agree(self, eq_data, log_K):
        """``_get_log_nK_jit`` (one molecule) vs ``_mol_log_nK_all_jit`` (all)."""
        T = 5000.0
        all_vals = np.asarray(S._mol_log_nK_all_jit(T, eq_data))
        for idx in (0, 1, 5, eq_data.n_molecules - 1):
            one = float(S._get_log_nK_jit(idx, np.log(T), eq_data))
            if np.isfinite(all_vals[idx]):
                assert one == pytest.approx(all_vals[idx], rel=1e-12), f"mol {idx}"

    def test_cubic_spline_eval_logK_is_finite_on_the_grid(self, eq_data):
        for T in (2500.0, 5000.0, 15000.0):
            v = float(S._cubic_spline_eval_logK(np.log(T), eq_data, 0))
            assert np.isfinite(v)


class TestLegacyResiduals:
    """``_compute_residuals_jit`` has no callers anywhere in the package.

    It is kept because deleting a solver residual is a bigger decision than this
    change; these tests at least prove it still runs and record its quirk.
    """

    def test_runs_and_returns_the_right_shape(self, eq_data, abundances):
        x = jnp.concatenate([jnp.full(S.MAX_ATOMIC_NUMBER, 10.0), jnp.array([13.0])])
        F = S._compute_residuals_jit(x, 1e16, abundances, eq_data)
        assert F.shape == (S.MAX_ATOMIC_NUMBER + 1,)
        assert np.all(np.isfinite(np.asarray(F)))

    def test_temperature_argument_is_ignored(self, eq_data, abundances):
        """Line 738 selects the temperature with ``x.shape[0] > 93``, which is
        never true for the 93-vector it is called with, so T is hard-wired to
        5777 K.  Recorded, not relied upon.
        """
        x = jnp.concatenate([jnp.full(S.MAX_ATOMIC_NUMBER, 10.0), jnp.array([13.0])])
        assert x.shape[0] == S.MAX_ATOMIC_NUMBER + 1
        F = S._compute_residuals_jit(x, 1e16, abundances, eq_data)
        assert np.all(np.isfinite(np.asarray(F)))

    def test_runs_without_molecules(self, eq_data_no_molecules, abundances):
        data = eq_data_no_molecules
        x = jnp.concatenate([jnp.full(S.MAX_ATOMIC_NUMBER, 10.0), jnp.array([13.0])])
        F = S._compute_residuals_jit(x, 1e16, abundances, data)
        assert np.all(np.isfinite(np.asarray(F)))


# ===========================================================================
# 1. FUNCTIONAL — solvers
# ===========================================================================

class TestPicardGuess:

    def test_returns_a_physical_electron_density(self, eq_data, abundances):
        ne, nf = S.picard_chemical_equilibrium_guess(5778.0, 1e17, 1e14,
                                                     abundances, eq_data)
        ne = float(ne)
        assert 0 < ne < 1e17
        nf = np.asarray(nf)
        assert nf.shape == (S.MAX_ATOMIC_NUMBER,)
        assert np.all((nf >= 0) & (nf <= 1 + 1e-12))

    def test_hotter_gas_is_more_ionized(self, eq_data, abundances):
        ne = [float(S.picard_chemical_equilibrium_guess(T, 1e17, 1e14,
                                                        abundances, eq_data)[0])
              for T in (4000.0, 6000.0, 9000.0)]
        assert ne == sorted(ne)

    def test_is_insensitive_to_the_initial_guess(self, eq_data, abundances):
        a = float(S.picard_chemical_equilibrium_guess(5778.0, 1e17, 1e10,
                                                      abundances, eq_data)[0])
        b = float(S.picard_chemical_equilibrium_guess(5778.0, 1e17, 1e16,
                                                      abundances, eq_data)[0])
        assert a == pytest.approx(b, rel=1e-6)


class TestChemicalEquilibriumFast:
    """Single-layer Picard driver; previously had no test at all."""

    def test_returns_a_populated_species_dict(self, eq_data, abundances):
        from korg.species import Species
        mol_species = [Species("H2"), Species("CO"), Species("OH")]
        ne, nd, raw = S.chemical_equilibrium_fast(5778.0, 1e17, 1e14, abundances,
                                                 eq_data, mol_species)
        assert 0 < float(ne) < 1e17
        assert Species("H I") in nd and Species("H II") in nd
        assert float(nd[Species("H I")]) > float(nd[Species("H II")])
        for key in ("neutral_dens", "ionized_dens", "doubly_ionized_dens", "mol_dens"):
            assert key in raw
        assert raw["neutral_dens"].shape == (S.MAX_ATOMIC_NUMBER,)

    def test_densities_are_non_negative_and_finite(self, eq_data, abundances):
        _, nd, raw = S.chemical_equilibrium_fast(4000.0, 1e16, 1e12, abundances,
                                                 eq_data, [])
        for sp, v in nd.items():
            v = float(v)
            assert np.isfinite(v) and v >= 0, sp
        assert np.all(np.isfinite(np.asarray(raw["neutral_dens"])))


class TestChemicalEquilibriumAllLayers:
    """The all-layer driver used by ``synthesis``; previously untested."""

    T_ARR = np.array([4000.0, 5778.0, 8000.0])
    NT_ARR = np.array([1e17, 1e17, 5e16])
    NE_ARR = np.array([1e12, 1e14, 1e15])

    def test_shapes_and_physicality(self, eq_data, abundances):
        from korg.species import Species
        ne, nd, raw = S.chemical_equilibrium_all_layers(
            self.T_ARR, self.NT_ARR, self.NE_ARR, abundances, eq_data,
            [Species("H2"), Species("CO")])
        ne = np.asarray(ne)
        assert ne.shape == (3,)
        assert np.all(np.isfinite(ne)) and np.all(ne > 0)
        assert len(raw) == 3
        assert np.all(np.diff(ne / self.NT_ARR) > 0), "ionization must grow with T"
        assert Species("H I") in nd

    def test_without_molecules(self, eq_data_no_molecules, abundances):
        """The ``data.n_molecules == 0`` branch."""
        data = eq_data_no_molecules
        ne, nd, raw = S.chemical_equilibrium_all_layers(
            self.T_ARR, self.NT_ARR, self.NE_ARR, abundances, data, [])
        assert np.asarray(ne).shape == (3,)
        assert np.all(np.asarray(ne) > 0)

    def test_bounded_disagreement_with_the_newton_solver(self, eq_data, abundances):
        """``chemical_equilibrium_all_layers`` does *not* call the Newton solver.

        It runs Picard plus a hand-rolled numpy fixed point, so it is a third,
        independent route to the same physics (the others being
        ``_chem_eq_newton_batch_jit`` and ``tests/reference_chemical_equilibrium``).
        They agree closely where hydrogen ionization dominates and drift apart at
        low temperature where molecules matter.

        This bounds the drift rather than asserting a particular value, so it
        catches a real regression without freezing in the current discrepancy.
        Reconciling the two drivers is a separate decision.
        """
        ne_all = np.asarray(S.chemical_equilibrium_all_layers(
            self.T_ARR, self.NT_ARR, self.NE_ARR, abundances, eq_data, [])[0])

        ne_g, nf_g = S._picard_chemical_equilibrium_guess_batch(
            jnp.asarray(self.T_ARR), jnp.asarray(self.NT_ARR),
            jnp.asarray(self.NE_ARR), abundances, eq_data)
        ne_newton = np.asarray(S._chem_eq_newton_batch_jit(
            jnp.asarray(self.T_ARR), jnp.asarray(self.NT_ARR), ne_g, nf_g,
            abundances, eq_data)[0])

        rel = np.abs(ne_all / ne_newton - 1.0)
        assert np.all(np.isfinite(rel))
        assert rel[-1] < 1e-3, "hot layers must agree closely"
        assert np.all(rel < 0.05), (
            f"drivers now disagree by {rel.max():.3%}, previously ~1%")


class TestNewtonScan:
    """``_chem_eq_newton_scan_jit`` is imported by synthesis but never called."""

    def test_matches_the_batched_newton_solver(self, eq_data, abundances):
        T = jnp.array([4000.0, 5778.0, 8000.0])
        nt = jnp.array([1e17, 1e17, 5e16])
        ne_m = jnp.array([1e12, 1e14, 1e15])
        ne_g, nf_g = S._picard_chemical_equilibrium_guess_batch(T, nt, ne_m,
                                                               abundances, eq_data)
        ne_scan = np.asarray(S._chem_eq_newton_scan_jit(T, nt, ne_g, nf_g,
                                                        abundances, eq_data)[0])
        ne_batch = np.asarray(S._chem_eq_newton_batch_jit(T, nt, ne_g, nf_g,
                                                          abundances, eq_data)[0])
        np.testing.assert_allclose(ne_scan, ne_batch, rtol=1e-6)


class TestLogSpaceSystem:

    def _y0(self, eq_data, abundances, T=5778.0, n_total=1e17, ne=1e14):
        ne_g, nf_g = S.picard_chemical_equilibrium_guess(T, n_total, ne,
                                                        abundances, eq_data)
        return jnp.concatenate([
            jnp.log10(jnp.clip(nf_g * abundances * (n_total - ne_g), 1e-99, jnp.inf)),
            jnp.array([jnp.log10(ne_g)])])

    def test_residuals_are_small_at_the_solution(self, eq_data, abundances):
        y = S._chem_eq_solve_log(5778.0, 1e17, abundances, eq_data,
                                 self._y0(eq_data, abundances))
        F = np.asarray(S._chem_eq_log_residuals(y, 5778.0, 1e17, abundances, eq_data))
        assert F.shape == (S.MAX_ATOMIC_NUMBER + 1,)
        assert np.max(np.abs(F)) < 1e-6

    def test_terms_are_physical(self, eq_data, abundances):
        y = S._chem_eq_solve_log(5778.0, 1e17, abundances, eq_data,
                                 self._y0(eq_data, abundances))
        (n_I, n_II, n_III, ne, n_mol, n_Hminus, n_nuclei,
         C, is_charged, log_wII) = S._chem_eq_log_terms(y, 5778.0, 1e17, abundances,
                                                        eq_data, 0.0)
        for arr in (n_I, n_II, n_III, n_mol):
            arr = np.asarray(arr)
            assert np.all(np.isfinite(arr)) and np.all(arr >= 0)
        assert float(ne) > 0 and float(n_nuclei) > 0
        assert 0 < float(n_Hminus) < float(n_I[0])
        assert set(np.unique(np.asarray(is_charged))) <= {0.0, 1.0}

    def test_undefined_equilibrium_constants_contribute_nothing(self, eq_data,
                                                                abundances):
        """Molecules whose log K is non-finite are dropped — and, importantly,
        their exponent is replaced *before* ``_pow10``, so no NaN cotangent
        leaks back through the masked branch."""
        log_nK = np.asarray(S._mol_log_nK_all_jit(5778.0, eq_data))
        y = self._y0(eq_data, abundances)
        terms = S._chem_eq_log_terms(y, 5778.0, 1e17, abundances, eq_data, 0.0)
        n_mol = np.asarray(terms[4])
        bad = ~np.isfinite(log_nK)
        if bad.any():
            assert np.all(n_mol[bad] == 0.0)
        assert np.all(np.isfinite(n_mol))

    def test_analytic_jacobian_matches_autodiff(self, eq_data, abundances):
        y = self._y0(eq_data, abundances)
        J = np.asarray(S._chem_eq_log_jacobian(y, 5778.0, 1e17, abundances, eq_data))
        J_ad = np.asarray(jax.jacfwd(S._chem_eq_log_residuals)(
            y, 5778.0, 1e17, abundances, eq_data))
        scale = np.maximum(np.abs(J_ad), 1e-12)
        assert np.max(np.abs(J - J_ad) / scale) < 1e-10


# ===========================================================================
# 3. AUTODIFF
# ===========================================================================

class TestAutodiff:

    def test_hummer_mihalas_w_grad_matches_finite_difference(self):
        args = (5778.0, 5.0, 1.8e17, 1.6e16, 1e14)
        for argnum in range(5):
            g = float(jax.grad(S.hummer_mihalas_w, argnums=argnum)(*args))

            def f(x, i=argnum):
                a = list(args)
                a[i] = x
                return float(S.hummer_mihalas_w(*a))

            fd = _central_difference(f, args[argnum])
            assert g == pytest.approx(fd, rel=1e-5, abs=1e-30), f"argnum={argnum}"
            if argnum != 0:
                assert g != 0.0, f"argnum={argnum} gradient is identically zero"

    def test_w_has_no_temperature_dependence_in_the_standard_branch(self):
        """H&M 4.71 without the Hubeny generalization contains no T at all.

        ``neutral_term`` depends only on n_eff, nH and nHe, and
        ``charged_term = 16 (e²/(χ√K))³ nₑ`` only on n_eff and nₑ.  So dw/dT is
        exactly zero — not merely small.  Asserted so that a future edit which
        introduces a spurious T dependence is caught.
        """
        args = (5.0, 1.8e17, 1.6e16, 1e14)
        assert float(jax.grad(S.hummer_mihalas_w, argnums=0)(5778.0, *args)) == 0.0
        assert (float(S.hummer_mihalas_w(3000.0, *args))
                == float(S.hummer_mihalas_w(9000.0, *args)))
        # the Hubeny branch *does* depend on T
        assert float(jax.grad(S.hummer_mihalas_w, argnums=0)(
            5778.0, *args, use_hubeny_generalization=True)) != 0.0

    @pytest.mark.parametrize("ne,T,label", [
        (0.0, 5778.0, "ne = 0"),
        (1e-300, 5778.0, "ne underflowed"),
        (1e14, 5.0, "T below the Hubeny guard"),
        (5.0, 5778.0, "ne below the Hubeny guard"),
    ])
    def test_hubeny_branch_does_not_leak_nan_cotangents(self, ne, T, label):
        """``jnp.where`` masks the *value* of the discarded Hubeny term but not
        its cotangent, so ``log(ne)`` at ne <= 0 and ``1/sqrt(T)`` at T <= 0 used
        to return NaN gradients for *all* of T, n_eff and ne.  The fix feeds the
        block strictly positive stand-ins before those operations.
        """
        g = jax.grad(S.hummer_mihalas_w, argnums=(0, 1, 2, 3, 4))(
            T, 5.0, 1.8e17, 1.6e16, ne, use_hubeny_generalization=True)
        g = [float(x) for x in g]
        assert all(np.isfinite(x) for x in g), f"{label}: {g}"

    def test_hummer_mihalas_U_H_grad_is_finite(self):
        g = float(jax.grad(S.hummer_mihalas_U_H, argnums=0)(5778.0, 1e16, 1e15, 1e13))
        assert np.isfinite(g) and g != 0.0

    def test_translational_U_grad(self):
        from korg.constants import electron_mass_cgs
        T = 5778.0
        g = float(jax.grad(lambda t: S.translational_U(electron_mass_cgs, t))(T))
        fd = _central_difference(
            lambda t: float(S.translational_U(electron_mass_cgs, t)), T)
        assert g == pytest.approx(fd, rel=1e-6)

    def test_Hminus_nK_grad(self):
        g = float(jax.grad(S.Hminus_nK)(5778.0))
        fd = _central_difference(lambda t: float(S.Hminus_nK(t)), 5778.0)
        assert g == pytest.approx(fd, rel=1e-6)

    def test_newton_layer_reverse_mode_wrt_abundances(self, eq_data, abundances,
                                                      layer_kernels):
        """The batched solver is reverse-mode differentiable via the
        implicit-function-theorem ``custom_jvp`` on ``_chem_eq_solve_log``."""
        T, nt = 5778.0, 1e17
        ne_g, nf_g = S.picard_chemical_equilibrium_guess(T, nt, 1e14, abundances,
                                                        eq_data)

        g = np.asarray(layer_kernels.d_ne_dab(jnp.float64(T), jnp.float64(nt),
                                              ne_g, nf_g, abundances))
        assert g.shape == (S.MAX_ATOMIC_NUMBER,)
        assert np.all(np.isfinite(g))
        assert np.linalg.norm(g) > 0

    def test_newton_layer_reverse_mode_matches_central_difference(self, eq_data,
                                                                  abundances,
                                                                  layer_kernels):
        T, nt = 5778.0, 1e17
        ne_g, nf_g = S.picard_chemical_equilibrium_guess(T, nt, 1e14, abundances,
                                                        eq_data)

        rev = float(layer_kernels.d_ne_dT(jnp.float64(T), jnp.float64(nt),
                                          ne_g, nf_g, abundances))
        assert np.isfinite(rev) and rev != 0.0
        assert rev == pytest.approx(
            _central_difference(lambda t: layer_kernels.at(t, nt, ne_g, nf_g,
                                                           abundances), T),
            rel=1e-5)

    def test_forward_and_reverse_mode_through_the_solver_agree(self, eq_data,
                                                               abundances,
                                                               layer_kernels):
        """Both modes work and give the same answer.

        ``_chem_eq_solve_log`` carries a ``custom_jvp`` whose rule is
        ``dy = -J⁻¹ ∂F/∂θ`` for θ = (T, n_total, abundances).  Reverse mode has
        always been correct; forward mode used to return NaN in all 93
        components, and this test previously pinned that.  The cause was not the
        rule but a guard inside ``_chem_eq_log_terms``:
        ``log10(maximum(wIII, 1e-320))``.  1e-320 is subnormal, XLA flushes
        subnormals to zero, so the floor never applied, and hydrogen --- which
        has no doubly ionized state, so wIII[0] is exactly 0 --- produced
        log10(0) = -Inf with a 1/0 derivative meeting a zero tangent.  It showed
        up in exactly the two residual components n_III[0] enters: index 0
        (hydrogen's nucleus balance) and index 92 (charge balance).
        """
        T, nt = 5778.0, 1e17
        ne_g, nf_g = S.picard_chemical_equilibrium_guess(T, nt, 1e14, abundances,
                                                        eq_data)
        args = (jnp.float64(nt), ne_g, nf_g, abundances)

        rev = float(layer_kernels.d_ne_dT(jnp.float64(T), *args))
        fwd = float(layer_kernels.jacfwd_T(jnp.float64(T), *args))
        assert np.isfinite(rev) and np.isfinite(fwd)
        assert fwd == pytest.approx(rev, rel=1e-12)
        assert fwd == pytest.approx(
            _central_difference(lambda t: layer_kernels.at(t, nt, ne_g, nf_g,
                                                           abundances), T),
            rel=1e-5)

    def test_custom_jvp_rule_is_the_implicit_function_theorem(self, eq_data,
                                                              abundances):
        """The registered tangent is exactly −J⁻¹ ∂F/∂T.

        Written to compare the *finite* structure rather than using
        ``assert_allclose``'s default ``equal_nan=True``: when both sides were
        NaN (see the test above, before the subnormal-floor fix) an allclose
        comparison passed vacuously.  Keeping the mask comparison means it stays
        honest if a NaN ever comes back.
        """
        T, nt = 5778.0, 1e17
        ne_g, nf_g = S.picard_chemical_equilibrium_guess(T, nt, 1e14, abundances,
                                                        eq_data)
        y0 = jnp.concatenate([
            jnp.log10(jnp.clip(nf_g * abundances * (nt - ne_g), 1e-99, jnp.inf)),
            jnp.array([jnp.log10(ne_g)])])

        y, dy = jax.jvp(lambda t: S._chem_eq_solve_log(t, nt, abundances, eq_data, y0),
                        (T,), (1.0,))
        assert np.all(np.isfinite(np.asarray(y))), "the primal solution is healthy"

        J = S._chem_eq_log_jacobian(y, T, nt, abundances, eq_data, 0.0)
        dF = jax.jvp(lambda t: S._chem_eq_log_residuals(y, t, nt, abundances, eq_data),
                     (T,), (1.0,))[1]
        expected = np.asarray(-jnp.linalg.solve(J, dF))
        dy = np.asarray(dy)
        np.testing.assert_array_equal(np.isnan(dy), np.isnan(expected))
        finite = ~np.isnan(dy)
        if finite.any():
            np.testing.assert_allclose(dy[finite], expected[finite], rtol=1e-8)

    def test_newton_scan_is_reverse_mode_differentiable(self, eq_data, abundances):
        """lax.scan (unlike lax.while_loop) supports reverse mode."""
        T = jnp.array([5000.0, 6000.0])
        nt = jnp.array([1e17, 1e17])
        ne_m = jnp.array([1e13, 1e14])
        ne_g, nf_g = S._picard_chemical_equilibrium_guess_batch(T, nt, ne_m,
                                                               abundances, eq_data)

        def f(scale):
            return jnp.sum(S._chem_eq_newton_scan_jit(T * scale, nt, ne_g, nf_g,
                                                      abundances, eq_data)[0])

        g = float(jax.grad(f)(1.0))
        assert np.isfinite(g) and g != 0.0

    def test_picard_is_forward_mode_only(self, eq_data, abundances):
        """``picard_chemical_equilibrium_guess`` runs ``lax.while_loop``, which
        JAX cannot transpose.  Forward mode works; reverse mode must raise, and
        it must raise for *this* reason rather than silently returning zeros.
        """
        def f(T):
            return S.picard_chemical_equilibrium_guess(T, 1e17, 1e14, abundances,
                                                       eq_data)[0]

        fwd = float(jax.jacfwd(f)(5778.0))
        assert np.isfinite(fwd) and fwd != 0.0
        assert fwd == pytest.approx(_central_difference(lambda t: float(f(t)), 5778.0),
                                    rel=1e-4)

        with pytest.raises(ValueError, match="Reverse-mode differentiation"):
            jax.grad(f)(5778.0)

    def test_picard_and_newton_derivatives_are_consistent(self, eq_data, abundances):
        """Two different solvers, two different AD paths, one physical answer."""
        T, nt = 5778.0, 1e17

        def picard(t):
            return S.picard_chemical_equilibrium_guess(t, nt, 1e14, abundances,
                                                       eq_data)[0]

        ne_g, nf_g = S.picard_chemical_equilibrium_guess(T, nt, 1e14, abundances,
                                                        eq_data)

        def newton(t):
            return S._chem_eq_newton_layer_jit(t, nt, ne_g, nf_g, abundances,
                                               eq_data)[0]

        d_picard = float(jax.jacfwd(picard)(T))
        d_newton = float(jax.grad(newton)(T))
        assert d_picard == pytest.approx(d_newton, rel=2e-3)

    def test_saha_weights_grad_wrt_temperature_is_finite(self, eq_data):
        g = jax.grad(lambda T: jnp.sum(S._compute_saha_weights_jit(T, 1e14,
                                                                  eq_data)[0]))(5778.0)
        assert np.isfinite(float(g))


# ===========================================================================
# 4. JIT TRACING
# ===========================================================================

class TestJitTracing:

    def test_pure_functions_jit(self):
        from korg.constants import electron_mass_cgs
        assert np.isfinite(float(jax.jit(S.Hminus_nK)(5778.0)))
        assert np.isfinite(float(jax.jit(
            lambda T: S.translational_U(electron_mass_cgs, T))(5778.0)))
        assert np.isfinite(float(jax.jit(
            lambda T, ne: S.hummer_mihalas_w(T, 5.0, 1e17, 1e16, ne))(5778.0, 1e14)))

    def test_hummer_mihalas_w_hubeny_flag_must_be_static(self):
        """The Hubeny selector is a Python ``if``, so a *traced* bool cannot
        choose between the branches.

        The sibling implementation in ``korg.hydrogen_line_absorption`` uses
        ``jnp.where`` and does accept a traced flag; that difference is deliberate
        there (it is called with a traced flag) and irrelevant here (continuum.py
        always passes a literal).
        """
        with pytest.raises(jax.errors.TracerBoolConversionError):
            jax.jit(lambda flag: S.hummer_mihalas_w(5778.0, 5.0, 1e17, 1e16, 1e14,
                                                    use_hubeny_generalization=flag)
                    )(jnp.bool_(True))

    def test_hummer_mihalas_w_static_flag_jits(self):
        for flag in (False, True):
            f = jax.jit(lambda T: S.hummer_mihalas_w(
                T, 5.0, 1e17, 1e16, 1e14, use_hubeny_generalization=flag))
            assert np.isfinite(float(f(5778.0)))

    def test_solver_helpers_jit(self, eq_data, abundances):
        T, nt = 5778.0, 1e17
        ne_g, nf_g = S.picard_chemical_equilibrium_guess(T, nt, 1e14, abundances,
                                                        eq_data)
        f = jax.jit(lambda t, n: S._chem_eq_newton_layer_jit(t, n, ne_g, nf_g,
                                                             abundances, eq_data))
        ne, nf = f(T, nt)
        assert np.isfinite(float(ne)) and float(ne) > 0
        assert np.all(np.isfinite(np.asarray(nf)))

    def test_mol_densities_jit_and_vmap(self, eq_data, abundances):
        T = jnp.array([4000.0, 6000.0])
        nt = jnp.array([1e17, 1e17])
        ne = jnp.array([1e12, 1e14])
        nf = jnp.ones((2, S.MAX_ATOMIC_NUMBER)) * 0.9
        out = S._compute_mol_densities_batch_jit(T, nt, ne, abundances, nf, eq_data)
        assert out.shape == (2, eq_data.n_molecules)
        assert np.all(np.isfinite(np.asarray(out)))
        assert np.all(np.asarray(out) >= 0)

    def test_saha_weights_batch_jit(self, eq_data):
        T = jnp.array([4000.0, 6000.0, 9000.0])
        ne = jnp.array([1e12, 1e14, 1e15])
        wII, wIII = S._compute_saha_weights_batch_jit(T, ne, eq_data)
        assert wII.shape == (3, S.MAX_ATOMIC_NUMBER)
        assert np.all(np.isfinite(np.asarray(wII)))
        assert np.all(np.asarray(wIII)[:, 0] == 0.0), "H cannot be doubly ionized"

    def test_saha_ion_weights_cannot_be_jitted(self):
        """It indexes ``partition_funcs`` with a ``Species`` built from a Python
        ``int`` and branches on ``atom == 1``, so the element index can never be
        a tracer.  The vmapped ``_compute_saha_weights_jit`` exists for that.
        """
        from korg.data_loader import (load_ionization_energies,
                                      load_atomic_partition_functions)
        ie = load_ionization_energies()
        pf = load_atomic_partition_functions()
        with pytest.raises((jax.errors.TracerIntegerConversionError, TypeError,
                            KeyError, jax.errors.TracerBoolConversionError)):
            jax.jit(lambda Z: S.saha_ion_weights(5778.0, 1e14, Z, ie, pf)[0])(
                jnp.int32(26))

    def test_precompute_cannot_be_jitted(self, ionization_energies, partition_funcs,
                                         log_K):
        """It builds NumPy arrays, iterates Python dicts and calls spline objects,
        none of which survive tracing."""
        with pytest.raises(Exception):
            jax.jit(lambda t: S.precompute_chemical_equilibrium_data(
                ionization_energies, partition_funcs, log_K, T_min=t))(2000.0)
