"""
End-to-end tests for korg.synthesize() against Julia Korg.jl reference.

The Julia reference (julia_solar_synthesis.h5) is generated by
tests/generate_solar_synthesis_reference.jl and committed as a CI artifact.

These tests call korg.synthesize() as a black box with the same inputs Julia
used and compare the continuum-normalised output.  The Na I line at 6000 Å
is a simple, single-line case that exercises the full synthesis pipeline:
  chemical_equilibrium → line_absorption → radiative_transfer
"""

from pathlib import Path

import korg  # noqa: F401 — ensures JAX x64 mode

import numpy as np
import pytest

REFERENCE_FILE = Path(__file__).parent.parent / "julia_solar_synthesis.h5"
ATM_FILE = Path(__file__).parent / "data" / "sun.mod"


@pytest.fixture(scope="module")
def julia_ref():
    """Load Julia reference data from HDF5."""
    try:
        import h5py
    except ImportError:
        pytest.skip("h5py not installed")
    if not REFERENCE_FILE.exists():
        pytest.skip(f"Julia reference HDF5 not found: {REFERENCE_FILE}. "
                    "Run: julia --project=. tests/generate_solar_synthesis_reference.jl")
    with h5py.File(REFERENCE_FILE, "r") as f:
        return {
            "wavelengths": np.array(f["wavelengths"]),
            "flux": np.array(f["flux"]),
            "continuum": np.array(f["continuum"]),
            "cnorm": np.array(f["continuum_normalized_flux"]),
            "line": {k: float(np.array(f[f"line/{k}"])) for k in
                     ["wavelength_angstrom", "log_gf", "E_lower_eV",
                      "gamma_rad", "gamma_stark", "vdW_sigma", "vdW_alpha"]},
        }


@pytest.fixture(scope="module")
def python_result(julia_ref):
    """Run korg.synthesize() with the same inputs as the Julia reference."""
    if not ATM_FILE.exists():
        pytest.skip(f"Solar atmosphere file not found: {ATM_FILE}")

    from korg.linelist import Line
    from korg.species import Species
    from korg.atomic_data import grevesse_2007_solar_abundances

    atm = korg.read_model_atmosphere(str(ATM_FILE))
    line = julia_ref["line"]
    na_line = Line(
        wl=line["wavelength_angstrom"] * 1e-8,
        log_gf=line["log_gf"],
        species=Species("Na", 0),
        E_lower=line["E_lower_eV"],
        gamma_rad=line["gamma_rad"],
        gamma_stark=line["gamma_stark"],
        vdW=(line["vdW_sigma"], line["vdW_alpha"]),
    )

    wavelengths = julia_ref["wavelengths"]
    A_X = grevesse_2007_solar_abundances

    result = korg.synthesize(atm, [na_line], wavelengths, A_X,
                             hydrogen_lines=False, verbose=False)
    cnorm = np.asarray(result.flux) / np.asarray(result.continuum)
    return {"flux": np.asarray(result.flux), "continuum": np.asarray(result.continuum),
            "cnorm": cnorm}


# ---------------------------------------------------------------------------
# Julia comparison tests
# ---------------------------------------------------------------------------

class TestSynthesizeVsJulia:
    """Compare korg.synthesize() output to Julia Korg.jl for a Na I line."""

    def test_spectrum_shape(self, julia_ref, python_result):
        """Output wavelength grid has the same length as Julia's."""
        assert len(python_result["flux"]) == len(julia_ref["wavelengths"])

    def test_continuum_finite(self, python_result):
        """Continuum flux must be finite and positive everywhere."""
        assert np.all(np.isfinite(python_result["continuum"]))
        assert np.all(python_result["continuum"] > 0)

    def test_flux_finite(self, python_result):
        """Flux must be finite and non-negative."""
        assert np.all(np.isfinite(python_result["flux"]))
        assert np.all(python_result["flux"] >= 0)

    def test_cnorm_in_unit_interval(self, python_result):
        """Continuum-normalised flux must lie in [0, 1]."""
        cnorm = python_result["cnorm"]
        assert np.all(cnorm >= -0.01), "cnorm should not be significantly negative"
        assert np.all(cnorm <= 1.01), "cnorm should not exceed continuum"

    def test_line_is_absorption(self, julia_ref, python_result):
        """Na I line at 6000 Å must appear as an absorption feature."""
        i_center = np.argmin(python_result["cnorm"])
        wl_center = julia_ref["wavelengths"][i_center]
        assert abs(wl_center - 6000.0) < 0.5, \
            f"Line centre should be near 6000 Å, found {wl_center:.2f} Å"
        assert python_result["cnorm"][i_center] < 0.99, \
            "Expected at least 1% absorption at line centre"

    def test_line_depth_matches_julia(self, julia_ref, python_result):
        """Line depth (1 - min cnorm) agrees with Julia within 20%."""
        py_depth = 1.0 - python_result["cnorm"].min()
        jl_depth = 1.0 - julia_ref["cnorm"].min()
        assert abs(py_depth - jl_depth) / jl_depth < 0.20, \
            f"Line depth: Python={py_depth:.4f}, Julia={jl_depth:.4f}"

    def test_cnorm_rms_vs_julia(self, julia_ref, python_result):
        """Continuum-normalised spectrum matches Julia with RMS < 5%."""
        diff = python_result["cnorm"] - julia_ref["cnorm"]
        rms = np.sqrt(np.mean(diff**2))
        assert rms < 0.05, f"RMS residual {rms:.4f} exceeds 5% threshold"

    def test_continuum_shape_matches_julia(self, julia_ref, python_result):
        """Continuum shape (relative to its mean) matches Julia within 5%."""
        py_c = python_result["continuum"]
        jl_c = julia_ref["continuum"]
        py_norm = py_c / py_c.mean()
        jl_norm = jl_c / jl_c.mean()
        diff = np.abs(py_norm - jl_norm)
        assert diff.max() < 0.05, \
            f"Continuum shape max deviation {diff.max():.4f} exceeds 5%"


# ---------------------------------------------------------------------------
# Self-consistency tests (no Julia reference required)
# ---------------------------------------------------------------------------

class TestSynthesizeSelfConsistency:
    """Self-consistency checks for synthesize() that don't need Julia reference."""

    @pytest.fixture(scope="class")
    def continuum_only(self):
        """Synthesize continuum-only (empty linelist) for a narrow window."""
        if not ATM_FILE.exists():
            pytest.skip(f"Solar atmosphere not found: {ATM_FILE}")
        from korg.atomic_data import grevesse_2007_solar_abundances

        atm = korg.read_model_atmosphere(str(ATM_FILE))
        wls = np.linspace(5000.0, 5010.0, 50)
        result = korg.synthesize(atm, [], wls, grevesse_2007_solar_abundances,
                                 hydrogen_lines=False, verbose=False)
        return result

    def test_empty_linelist_flux_equals_continuum(self, continuum_only):
        """With no lines, flux / continuum should be ≈ 1 everywhere."""
        flux = np.asarray(continuum_only.flux)
        cntm = np.asarray(continuum_only.continuum)
        ratio = flux / cntm
        np.testing.assert_allclose(ratio, 1.0, atol=1e-3,
                                   err_msg="flux/continuum ≠ 1 for empty linelist")

    def test_continuum_positive_finite(self, continuum_only):
        """Continuum flux is always positive and finite."""
        cntm = np.asarray(continuum_only.continuum)
        assert np.all(np.isfinite(cntm))
        assert np.all(cntm > 0)

    def test_line_deepens_absorption(self):
        """Adding a line reduces flux at line centre relative to continuum-only."""
        if not ATM_FILE.exists():
            pytest.skip(f"Solar atmosphere not found: {ATM_FILE}")
        from korg.linelist import create_line
        from korg.atomic_data import grevesse_2007_solar_abundances

        atm = korg.read_model_atmosphere(str(ATM_FILE))
        A_X = grevesse_2007_solar_abundances
        wls = np.linspace(4999.0, 5001.0, 100)

        # A moderately strong Fe I line
        fe_line = create_line(5000.0, 0.0, "Fe I", 1.0)

        result_line = korg.synthesize(atm, [fe_line], wls, A_X,
                                      hydrogen_lines=False, verbose=False)
        result_cntm = korg.synthesize(atm, [], wls, A_X,
                                      hydrogen_lines=False, verbose=False)

        cnorm = np.asarray(result_line.flux) / np.asarray(result_line.continuum)
        i_center = np.argmin(np.abs(wls - 5000.0))

        # Line should produce at least some absorption
        assert cnorm[i_center] < 0.99, \
            f"Expected absorption at line centre, got cnorm={cnorm[i_center]:.4f}"
