"""
Bounds checking for continuum absorption, and the four sources Korg.jl wraps.

Korg.jl v1.2.1 wraps ``Hminus_bf``, ``Hminus_ff``, ``H2plus_bf_and_ff`` and
``Heminus_ff`` in ``bounds_checked_absorption``, which returns *exactly zero*
outside the range each underlying table is valid over.  Korg.px used to
extrapolate instead — off the end of a bilinear interpolant, with no error
control and no comment saying it was intended.  These tests pin the adopted
Julia behaviour against freshly generated references.

Four categories, matching the project's test taxonomy:

1. Functional — bounds in both directions, the ``error_oobounds`` flag,
   exactly-on-boundary inputs, degenerate inputs.
2. High-precision agreement with Korg.jl (``tests/chemistry_reference_data.json``,
   generated by ``tests/generate_chemistry_reference.jl``).
3. Autodiff — ``jax.grad`` finite and matching central differences.
4. jit-tracing — what traces, and what provably cannot.
"""

import json
import os

import jax
import jax.numpy as jnp
import numpy as np
import pytest

import korg  # noqa: F401 — side effect: enables x64
from korg import continuum as C
from korg.constants import c_cgs
from korg.continuum_absorption import bounds_checking as B
from korg.continuum_absorption.bounds_checking import (
    Interval, closed_interval, contained, contained_slice, lambda_to_nu_bound,
    bounds_checked_absorption, in_bounds_mask, clamp_to_bound,
    HMINUS_BF_NU_BOUND, HMINUS_BF_TEMP_BOUND,
    HMINUS_FF_NU_BOUND, HMINUS_FF_TEMP_BOUND,
    H2PLUS_NU_BOUND, H2PLUS_TEMP_BOUND,
    HEMINUS_FF_NU_BOUND, HEMINUS_FF_TEMP_BOUND,
)

REFERENCE_FILE = os.path.join(os.path.dirname(__file__), "chemistry_reference_data.json")
JULIA_REFERENCE_FILE = os.path.join(os.path.dirname(__file__), "julia_reference_data.json")


def _load(path):
    if not os.path.exists(path):
        return {}
    with open(path) as f:
        return json.load(f)


@pytest.fixture(scope="module")
def chem_ref():
    data = _load(REFERENCE_FILE)
    if not data:
        pytest.skip("chemistry_reference_data.json missing; "
                    "run tests/generate_chemistry_reference.jl")
    return data


@pytest.fixture(scope="module")
def julia_ref():
    return _load(JULIA_REFERENCE_FILE)


def nu_of_A(lambda_A):
    """Frequency (Hz) of a wavelength given in Å, matching the Julia generator."""
    return c_cgs / (lambda_A * 1e-8)


def _as_float(x):
    """JSON round-trip helper: the generator stringifies Inf/NaN."""
    return float(x)


# ===========================================================================
# 1. FUNCTIONAL — interval primitives
# ===========================================================================

class TestIntervalPrimitives:
    """Interval algebra, exclusive vs closed, and the λ→ν conversion."""

    def test_interval_is_exclusive_by_default(self):
        iv = Interval(3.0, 10.0)
        assert contained(5.0, iv)
        assert not contained(3.0, iv)
        assert not contained(10.0, iv)

    def test_closed_interval_admits_its_endpoints(self):
        iv = closed_interval(3.0, 10.0)
        assert contained(3.0, iv)
        assert contained(10.0, iv)
        assert contained(5.0, iv)
        assert not contained(2.0, iv)
        assert not contained(11.0, iv)

    def test_closed_interval_nudges_outward_by_one_ulp(self):
        """closed_interval widens by one ULP; that is *how* it becomes inclusive."""
        iv = closed_interval(1400.0, 10080.0)
        assert iv.lower < 1400.0
        assert iv.upper > 10080.0
        assert iv.lower == np.nextafter(1400.0, -np.inf)
        assert iv.upper == np.nextafter(10080.0, np.inf)

    def test_interval_rejects_inverted_bounds(self):
        with pytest.raises(ValueError, match="upper bound must exceed"):
            Interval(10.0, 3.0)
        with pytest.raises(ValueError):
            Interval(5.0, 5.0)

    def test_infinite_endpoints_are_not_nudged(self):
        iv = closed_interval(0.0, np.inf)
        assert iv.upper == np.inf
        assert contained(1e300, iv)
        assert not contained(np.inf, iv)

    @pytest.mark.parametrize("vals,lo,hi,expected", [
        ([1.0, 2.0, 4.0, 5.0, 6.0, 8.0, 9.0, 12.0], 3.0, 10.0, [4.0, 5.0, 6.0, 8.0, 9.0]),
        # every value below the interval
        ([1.0, 2.0, 3.0], 10.0, 20.0, []),
        # every value above the interval
        ([100.0, 200.0], 10.0, 20.0, []),
        # everything inside
        ([11.0, 12.0], 10.0, 20.0, [11.0, 12.0]),
    ])
    def test_contained_slice(self, vals, lo, hi, expected):
        sl = contained_slice(np.array(vals), closed_interval(lo, hi))
        assert isinstance(sl, slice)
        assert list(np.array(vals)[sl]) == expected

    def test_contained_slice_is_inclusive_of_endpoints(self):
        """searchsortedfirst..searchsortedlast admits values sitting on the bound.

        This asymmetry (ν inclusive, T exclusive) is Korg's, and it matters: see
        test_hminus_ff_lower_nu_bound_is_inclusive.
        """
        vals = np.array([1.0, 3.0, 5.0, 10.0, 12.0])
        sl = contained_slice(vals, Interval(3.0, 10.0))
        assert list(vals[sl]) == [3.0, 5.0, 10.0]

    def test_contained_slice_empty_input(self):
        sl = contained_slice(np.array([]), closed_interval(1.0, 2.0))
        assert sl == slice(0, 0)

    def test_lambda_to_nu_bound_reverses_the_interval(self):
        nu_b = lambda_to_nu_bound(closed_interval(1823e-8, 151890e-8))
        # short λ ↔ high ν
        assert nu_b.lower < nu_of_A(151890.0) * 1.001
        assert nu_b.upper > nu_of_A(1823.0) * 0.999
        assert nu_b.lower < nu_b.upper

    def test_lambda_to_nu_bound_handles_zero_wavelength(self):
        """λ = 0 maps to ν = ∞ without dividing by zero."""
        nu_b = lambda_to_nu_bound(Interval(0.0, 1e-3))
        assert np.isinf(nu_b.upper)
        assert np.isfinite(nu_b.lower)


# ===========================================================================
# 1. FUNCTIONAL — bounds_checked_absorption wrapper
# ===========================================================================

def _kernel(nu, T, scale=1.0):
    """Trivial absorption kernel: linear in ν so truncation is easy to see."""
    return scale * nu * T


class TestBoundsCheckedAbsorption:
    """Julia's NumPy-side wrapper: truncation, error_oobounds, out_alpha."""

    NU_BOUND = closed_interval(10.0, 100.0)
    T_BOUND = closed_interval(1000.0, 2000.0)

    def _wrapped(self):
        return bounds_checked_absorption(_kernel, nu_bound=self.NU_BOUND,
                                         temp_bound=self.T_BOUND)

    def test_all_in_bounds(self):
        f = self._wrapped()
        nus = np.array([20.0, 50.0, 90.0])
        out = f(nus, 1500.0)
        np.testing.assert_allclose(out, nus * 1500.0, rtol=0, atol=0)

    def test_truncates_below_and_above(self):
        f = self._wrapped()
        nus = np.array([1.0, 5.0, 20.0, 50.0, 500.0, 900.0])
        out = f(nus, 1500.0)
        assert out[0] == 0.0 and out[1] == 0.0      # below ν_bound
        assert out[4] == 0.0 and out[5] == 0.0      # above ν_bound
        np.testing.assert_allclose(out[2:4], nus[2:4] * 1500.0)

    def test_temperature_out_of_bounds_zeroes_everything(self):
        f = self._wrapped()
        nus = np.array([20.0, 50.0, 90.0])
        for T in (999.0, 2001.0, 0.0):
            np.testing.assert_array_equal(f(nus, T), np.zeros(3))

    def test_exactly_on_the_boundary_is_in_bounds(self):
        f = self._wrapped()
        nus = np.array([10.0, 100.0])
        for T in (1000.0, 2000.0):
            out = f(nus, T)
            assert np.all(out > 0), f"endpoint rejected at T={T}"

    def test_error_oobounds_raises_for_temperature(self):
        f = self._wrapped()
        with pytest.raises(ValueError, match="invalid temperature"):
            f(np.array([20.0, 50.0]), 5000.0, error_oobounds=True)

    def test_error_oobounds_raises_for_frequency(self):
        f = self._wrapped()
        with pytest.raises(ValueError, match="invalid frequency"):
            f(np.array([1.0, 20.0, 50.0]), 1500.0, error_oobounds=True)
        with pytest.raises(ValueError, match="invalid frequency"):
            f(np.array([20.0, 50.0, 5000.0]), 1500.0, error_oobounds=True)

    def test_error_oobounds_silent_when_everything_is_in_bounds(self):
        f = self._wrapped()
        out = f(np.array([20.0, 50.0]), 1500.0, error_oobounds=True)
        assert np.all(out > 0)

    def test_out_alpha_accumulates_in_place(self):
        f = self._wrapped()
        nus = np.array([20.0, 50.0])
        acc = np.ones(2, dtype=np.float64)
        ret = f(nus, 1500.0, out_alpha=acc)
        assert ret is acc, "must accumulate in place, like Julia's out_α"
        np.testing.assert_allclose(acc, 1.0 + nus * 1500.0)

    def test_out_alpha_length_mismatch_is_rejected(self):
        f = self._wrapped()
        with pytest.raises(AssertionError, match="same length"):
            f(np.array([20.0, 50.0]), 1500.0, out_alpha=np.zeros(3))

    def test_out_alpha_dtype_mismatch_is_rejected(self):
        f = self._wrapped()
        with pytest.raises(AssertionError, match="dtype mismatch"):
            f(np.array([20.0, 50.0]), 1500.0, out_alpha=np.zeros(2, dtype=np.float32))

    def test_extra_args_are_forwarded(self):
        f = self._wrapped()
        nus = np.array([20.0, 50.0])
        np.testing.assert_allclose(f(nus, 1500.0, 3.0), 3.0 * nus * 1500.0)

    def test_descending_frequencies_rejected(self):
        """Korg's contained_slice assumes ascending ν; say so instead of silently
        returning garbage (the previous implementation accepted descending input
        and then indexed it with an ascending slice)."""
        f = self._wrapped()
        with pytest.raises(ValueError, match="sorted in increasing order"):
            f(np.array([90.0, 50.0, 20.0]), 1500.0)

    def test_unsorted_frequencies_rejected(self):
        f = self._wrapped()
        with pytest.raises(AssertionError, match="sorted"):
            f(np.array([20.0, 90.0, 50.0]), 1500.0)

    def test_scalar_input_rejected(self):
        f = self._wrapped()
        with pytest.raises(ValueError, match="1-D array"):
            f(np.float64(20.0), 1500.0)

    def test_single_element_array(self):
        f = self._wrapped()
        np.testing.assert_allclose(f(np.array([50.0]), 1500.0), [50.0 * 1500.0])
        np.testing.assert_array_equal(f(np.array([5.0]), 1500.0), [0.0])

    def test_default_bounds_are_unrestricted(self):
        f = bounds_checked_absorption(_kernel)
        nus = np.array([1e-3, 1e3, 1e30])
        assert np.all(f(nus, 1.0) > 0)

    def test_wrapper_exposes_its_bounds(self):
        f = self._wrapped()
        assert f.nu_bound is self.NU_BOUND
        assert f.temp_bound is self.T_BOUND


class TestClampToBound:
    """clamp_to_bound must never hand a zero or an infinity to the arithmetic."""

    def test_identity_inside_the_interval(self):
        iv = closed_interval(10.0, 100.0)
        for x in (10.0, 50.0, 100.0):
            assert float(clamp_to_bound(x, iv, 1.0)) == x

    def test_folds_outside_values_inward(self):
        iv = closed_interval(10.0, 100.0)
        assert float(clamp_to_bound(-5.0, iv, 1.0)) == pytest.approx(10.0)
        assert float(clamp_to_bound(1e6, iv, 1.0)) == pytest.approx(100.0)

    def test_uses_the_floor_when_the_interval_reaches_zero(self):
        iv = Interval(0.0, np.inf)
        assert float(clamp_to_bound(0.0, iv, 1000.0)) == 1000.0
        assert float(clamp_to_bound(-1.0, iv, 1000.0)) == 1000.0

    def test_result_is_strictly_positive(self):
        """A zero substitute is not good enough: sqrt(0) has infinite derivative
        and 0*inf is NaN, so the cotangent would still be poisoned."""
        for iv in (Interval(0.0, np.inf), closed_interval(0.0, 1e19)):
            assert float(clamp_to_bound(0.0, iv, 1.0)) > 0.0
            assert float(clamp_to_bound(-1e30, iv, 1.0)) > 0.0

    def test_infinite_upper_bound_is_left_unbounded(self):
        """Substituting a finite sentinel would silently alter in-bounds values."""
        iv = Interval(0.0, np.inf)
        assert float(clamp_to_bound(1e300, iv, 1.0)) == 1e300

    def test_non_positive_floor_rejected(self):
        with pytest.raises(ValueError, match="strictly positive"):
            clamp_to_bound(1.0, Interval(0.0, np.inf), 0.0)
        with pytest.raises(ValueError, match="strictly positive"):
            clamp_to_bound(1.0, Interval(0.0, np.inf), -1.0)

    def test_floor_above_upper_bound_rejected(self):
        with pytest.raises(ValueError, match="exceeds the interval upper bound"):
            clamp_to_bound(1.0, closed_interval(0.0, 5.0), 10.0)


class TestInBoundsMask:
    """The JAX-traceable mask, including Korg's ν/T asymmetry."""

    def test_nu_bound_is_inclusive(self):
        iv = closed_interval(10.0, 100.0)
        assert bool(in_bounds_mask(iv.lower, 1.0, iv, None))
        assert bool(in_bounds_mask(iv.upper, 1.0, iv, None))

    def test_temp_bound_is_exclusive_on_the_nudged_bounds(self):
        iv = closed_interval(1400.0, 10080.0)
        assert bool(in_bounds_mask(1.0, 1400.0, None, iv))     # nudged, so admitted
        assert bool(in_bounds_mask(1.0, 10080.0, None, iv))
        assert not bool(in_bounds_mask(1.0, iv.lower, None, iv))
        assert not bool(in_bounds_mask(1.0, iv.upper, None, iv))

    def test_none_means_unrestricted(self):
        assert bool(in_bounds_mask(1e30, 1e30, None, None))

    def test_vectorises_over_frequency(self):
        iv = closed_interval(10.0, 100.0)
        m = in_bounds_mask(jnp.array([1.0, 50.0, 1000.0]), 1.0, iv, None)
        assert list(np.asarray(m)) == [False, True, False]

    def test_traceable_under_jit(self):
        iv = closed_interval(10.0, 100.0)
        tv = closed_interval(1000.0, 2000.0)
        f = jax.jit(lambda nu, T: in_bounds_mask(nu, T, iv, tv))
        assert bool(f(50.0, 1500.0))
        assert not bool(f(5.0, 1500.0))
        assert not bool(f(50.0, 5.0))


# ===========================================================================
# 2. HIGH-PRECISION AGREEMENT WITH KORG.JL
# ===========================================================================

class TestBoundConstantsMatchJulia:
    """The bound endpoints must be bit-identical, not merely close.

    They are computed by a fixed-point ULP walk (``_convert_lambda_endpoint``),
    so a one-bit difference flips the answer at a table edge from the correct
    value to exactly zero.
    """

    NAMES = {
        "Hminus_bf_nu": HMINUS_BF_NU_BOUND,
        "Hminus_bf_temp": HMINUS_BF_TEMP_BOUND,
        "Hminus_ff_nu": HMINUS_FF_NU_BOUND,
        "Hminus_ff_temp": HMINUS_FF_TEMP_BOUND,
        "H2plus_nu": H2PLUS_NU_BOUND,
        "H2plus_temp": H2PLUS_TEMP_BOUND,
        "Heminus_ff_nu": HEMINUS_FF_NU_BOUND,
        "Heminus_ff_temp": HEMINUS_FF_TEMP_BOUND,
    }

    @pytest.mark.parametrize("name", sorted(NAMES))
    def test_endpoints_bit_identical(self, chem_ref, name):
        ref = chem_ref["bounds"]["intervals"][name]
        iv = self.NAMES[name]
        assert float(iv.lower) == _as_float(ref["lower"]), f"{name}.lower"
        assert float(iv.upper) == _as_float(ref["upper"]), f"{name}.upper"

    def test_contained_matches_julia_at_every_probe(self, chem_ref):
        probe_to_interval = {
            "Hminus_ff_nu": HMINUS_FF_NU_BOUND,
            "Heminus_ff_nu": HEMINUS_FF_NU_BOUND,
            "H2plus_nu": H2PLUS_NU_BOUND,
            "Hminus_bf_nu": HMINUS_BF_NU_BOUND,
            "Hminus_ff_temp": HMINUS_FF_TEMP_BOUND,
            "H2plus_temp": H2PLUS_TEMP_BOUND,
            "unbounded_temp": Interval(0, np.inf),
        }
        for name, cases in chem_ref["bounds"]["contained"].items():
            iv = probe_to_interval[name]
            for value_str, expected in cases.items():
                got = bool(contained(float(value_str), iv))
                assert got == expected, (
                    f"{name}: contained({value_str}) = {got}, Julia says {expected}")

    def test_contained_slice_matches_julia(self, chem_ref):
        ref = chem_ref["bounds"]["contained_slice"]
        vals = np.array([_as_float(v) for v in ref["values"]])
        sl = contained_slice(vals, HMINUS_FF_NU_BOUND)
        # Julia reports 1-based inclusive indices
        assert sl.start == ref["first"] - 1
        assert sl.stop == ref["last"]
        np.testing.assert_array_equal(vals[sl],
                                      [_as_float(v) for v in ref["selected"]])


class TestContinuumSourcesMatchJuliaOutOfBounds:
    """Each source across 14 temperatures × 15 wavelengths, in and out of bounds.

    ``rtol=1e-13`` — these are deterministic table lookups; the observed
    disagreement is a few ULP.
    """

    RTOL = 1e-13

    def _cases(self, chem_ref, source):
        ob = chem_ref["continuum_oob"]
        for key, ref in ob["outputs"][source].items():
            T, lam = (float(x) for x in key.split("_"))
            yield key, T, lam, _as_float(ref)

    def test_Hminus_ff(self, chem_ref):
        inp = chem_ref["continuum_oob"]["inputs"]
        n_zero = n_pos = 0
        for key, T, lam, ref in self._cases(chem_ref, "Hminus_ff"):
            got = float(C.Hminus_ff(nu_of_A(lam), T, inp["nH_I_div_U"], inp["ne"]))
            if ref == 0.0:
                assert got == 0.0, f"{key}: Julia returns exactly 0, got {got}"
                n_zero += 1
            else:
                assert got == pytest.approx(ref, rel=self.RTOL), key
                n_pos += 1
        assert n_zero > 0 and n_pos > 0

    def test_Heminus_ff(self, chem_ref):
        inp = chem_ref["continuum_oob"]["inputs"]
        n_zero = n_pos = 0
        for key, T, lam, ref in self._cases(chem_ref, "Heminus_ff"):
            got = float(C.Heminus_ff(nu_of_A(lam), T, inp["nHe_I_div_U"], inp["ne"]))
            if ref == 0.0:
                assert got == 0.0, f"{key}: Julia returns exactly 0, got {got}"
                n_zero += 1
            else:
                assert got == pytest.approx(ref, rel=self.RTOL), key
                n_pos += 1
        assert n_zero > 0 and n_pos > 0

    def test_H2plus_bf_and_ff(self, chem_ref):
        inp = chem_ref["continuum_oob"]["inputs"]
        n_zero = n_pos = 0
        for key, T, lam, ref in self._cases(chem_ref, "H2plus_bf_and_ff"):
            got = float(C.H2plus_bf_and_ff(nu_of_A(lam), T, inp["nH_I"], inp["nH_II"]))
            if ref == 0.0:
                assert got == 0.0, f"{key}: Julia returns exactly 0, got {got}"
                n_zero += 1
            else:
                assert got == pytest.approx(ref, rel=self.RTOL), key
                n_pos += 1
        assert n_zero > 0 and n_pos > 0

    def test_Hminus_bf_per_unit_density(self, chem_ref):
        """Korg v1.2 passes n(H⁻) from chemical equilibrium; Korg.px derives it
        from n(H I, n=1) via Saha (the v1.1 convention).  Divide out the density
        so this compares the McLaughlin cross section, the stimulated-emission
        factor and the bounds — not the density convention.
        """
        inp = chem_ref["continuum_oob"]["inputs"]
        n_zero = n_pos = 0
        for key, T, lam, ref in self._cases(chem_ref, "Hminus_bf"):
            nu = nu_of_A(lam)
            per_ion = float(C.Hminus_bf(nu, T, 1.0, inp["ne"])
                            / C.ndens_Hminus(1.0, inp["ne"], T))
            got = per_ion * inp["n_Hminus"]
            if ref == 0.0:
                assert got == 0.0, f"{key}: Julia returns exactly 0, got {got}"
                n_zero += 1
            else:
                assert got == pytest.approx(ref, rel=self.RTOL), key
                n_pos += 1
        assert n_zero > 0 and n_pos > 0


class TestKnownDivergencesArePinned:
    """The divergences we chose to keep, asserted so they cannot drift silently."""

    def test_hminus_density_convention_differs_by_exactly_two_over_U(self, julia_ref):
        """Korg v1.2 folds U(H I) = 2 into its H⁻ coefficient; Korg.px divides by
        the actual partition function.  The ratio is exactly 2/U(H I)."""
        if "continuum_sources" not in julia_ref:
            pytest.skip("continuum_sources fixture missing")
        for label, block in julia_ref["continuum_sources"].items():
            ratio = block["nHminus_ground_state"] / block["nHminus_korg_v1_2"]
            expected = 2.0 / block["U_H_I"]
            assert ratio == pytest.approx(expected, rel=1e-13), label

    def test_H2plus_raw_kernel_reproduces_the_unwrapped_julia_fixture(self, julia_ref):
        """`julia_reference_data.json` was generated from Julia's *unwrapped*
        ``_H2plus_bf_and_ff``, which extrapolates below 3150 K and returns a
        negative absorption coefficient there.  Korg.px keeps that kernel under
        the same private name so the fixture stays meaningful, and exposes only
        the bounds-checked version publicly.

        Note the existing test in test_julia_reference.py compares these with
        ``np.isclose``'s default ``atol=1e-8``, which is larger than every value
        in the fixture — so it cannot actually detect a disagreement.  This one
        uses atol=0.
        """
        if "H2plus_bf_and_ff" not in julia_ref:
            pytest.skip("H2plus_bf_and_ff fixture missing")
        ref = julia_ref["H2plus_bf_and_ff"]
        inp = ref["inputs"]
        nu = nu_of_A(inp["temperature_test_wavelength_angstrom"])

        saw_negative = False
        for T_str, julia_val in ref["temperature_outputs"].items():
            T = float(T_str)
            raw = float(C._H2plus_bf_and_ff(nu, T, inp["nH_I"], inp["nH_II"]))
            assert raw == pytest.approx(julia_val, rel=1e-10, abs=0.0), f"T={T}"
            if julia_val < 0:
                saw_negative = True
                # ... and the public entry point refuses to return it
                assert float(C.H2plus_bf_and_ff(nu, T, inp["nH_I"], inp["nH_II"])) == 0.0
        assert saw_negative, "fixture no longer exercises the extrapolated region"

    def test_hminus_ff_lower_nu_bound_is_inclusive(self):
        """ν = c/(151890·1e-8) lands *exactly* on ``HMINUS_FF_NU_BOUND.lower``.

        ``contained`` (exclusive) would reject it; Korg's wrapper selects
        frequencies with ``contained_slice`` (inclusive), so it is in bounds and
        returns a finite value.  Getting this wrong silently zeroes the reddest
        point of the Bell & Berrington table.
        """
        nu = nu_of_A(151890.0)
        assert nu == HMINUS_FF_NU_BOUND.lower
        assert not contained(nu, HMINUS_FF_NU_BOUND)
        assert bool(in_bounds_mask(nu, 5000.0, HMINUS_FF_NU_BOUND, HMINUS_FF_TEMP_BOUND))
        assert float(C.Hminus_ff(nu, 5000.0, 1e16, 1e13)) > 0.0

    def test_heminus_ff_admits_lambda_5063_exactly(self):
        """λ = 5063 Å is the first row of John (1994) and is in bounds."""
        assert float(C.Heminus_ff(nu_of_A(5063.0), 5000.0, 1e15, 1e13)) > 0.0
        assert float(C.Heminus_ff(nu_of_A(5062.0), 5000.0, 1e15, 1e13)) == 0.0


# ===========================================================================
# 1. FUNCTIONAL — physical limits of each source
# ===========================================================================

class TestSourcePhysicalLimits:

    NH_I_DIV_U = 1e16
    NHE_I_DIV_U = 1e15
    NE = 1e13

    def test_zero_electron_density_gives_zero(self):
        """Every ff source is ∝ P_e = n_e k T."""
        nu = nu_of_A(8000.0)
        assert float(C.Hminus_ff(nu, 5000.0, self.NH_I_DIV_U, 0.0)) == 0.0
        assert float(C.Heminus_ff(nu, 5000.0, self.NHE_I_DIV_U, 0.0)) == 0.0
        assert float(C.Hminus_bf(nu, 5000.0, self.NH_I_DIV_U, 0.0)) == 0.0

    def test_zero_absorber_density_gives_zero(self):
        nu = nu_of_A(8000.0)
        assert float(C.Hminus_ff(nu, 5000.0, 0.0, self.NE)) == 0.0
        assert float(C.Heminus_ff(nu, 5000.0, 0.0, self.NE)) == 0.0
        assert float(C.H2plus_bf_and_ff(nu, 5000.0, 0.0, 1e12)) == 0.0
        assert float(C.H2plus_bf_and_ff(nu, 5000.0, 1e17, 0.0)) == 0.0

    def test_hminus_bf_is_zero_below_the_ionization_threshold(self):
        """H⁻ binds by 0.754204 eV, i.e. λ > 16439 Å cannot detach it."""
        assert float(C.Hminus_bf(nu_of_A(20000.0), 5000.0,
                                 self.NH_I_DIV_U, self.NE)) == 0.0
        assert float(C.Hminus_bf(nu_of_A(16000.0), 5000.0,
                                 self.NH_I_DIV_U, self.NE)) > 0.0

    def test_hminus_bf_cross_section_regions(self):
        """Below threshold → 0; between threshold and the table → the (ν-ν₀)^1.5
        power law; above → the McLaughlin table."""
        nu_ion = C._Hminus_ion_nu
        nu_min = C._Hminus_min_nu
        assert float(C.Hminus_bf_cross_section(nu_ion)) == 0.0
        assert float(C.Hminus_bf_cross_section(nu_ion * 0.5)) == 0.0
        assert nu_ion < nu_min, "there must be an extrapolation region to test"
        mid = 0.5 * (nu_ion + nu_min)
        sigma_extrap = float(C.Hminus_bf_cross_section(mid))
        assert sigma_extrap > 0
        # power law: σ(2x) / σ(x) = 2^1.5 measured from the threshold
        a = float(C.Hminus_bf_cross_section(nu_ion + 0.1 * (nu_min - nu_ion)))
        b = float(C.Hminus_bf_cross_section(nu_ion + 0.4 * (nu_min - nu_ion)))
        assert b / a == pytest.approx(4.0**1.5, rel=1e-9)

    def test_hminus_ff_grows_towards_the_infrared(self):
        args = (5000.0, self.NH_I_DIV_U, self.NE)
        vals = [float(C.Hminus_ff(nu_of_A(l), *args))
                for l in (2000.0, 5000.0, 10000.0, 100000.0)]
        assert vals == sorted(vals)

    def test_electron_scattering_is_grey_and_linear(self):
        a1 = float(C.electron_scattering(1e13))
        a2 = float(C.electron_scattering(2e13))
        assert a2 == pytest.approx(2 * a1, rel=1e-14)
        assert float(C.electron_scattering(0.0)) == 0.0
        # Thomson cross section
        assert a1 / 1e13 == pytest.approx(6.652e-25, rel=1e-3)

    def test_rayleigh_falls_off_steeply_with_wavelength(self):
        vals = [float(C.rayleigh(nu_of_A(l), 1e17, 1e16, 1e12))
                for l in (3000.0, 5000.0, 10000.0)]
        assert vals[0] > vals[1] > vals[2] > 0
        # roughly λ^-4
        assert vals[0] / vals[1] > 5

    def test_rayleigh_is_zero_without_scatterers(self):
        assert float(C.rayleigh(nu_of_A(5000.0), 0.0, 0.0, 0.0)) == 0.0

    def test_ndens_state_He_I_ground_state_is_the_whole_population(self):
        """n=1 has g=1 and E=0, so n(He I, 1) = n(He I)/U exactly."""
        assert float(C.ndens_state_He_I(1, 1e15, 5000.0)) == 1e15

    @pytest.mark.parametrize("n,g", [(2, 3.0), (3, 1.0), (4, 9.0)])
    def test_ndens_state_He_I_excited_states(self, n, g):
        v = float(C.ndens_state_He_I(n, 1e15, 5000.0))
        assert 0 < v < 1e15 * g

    def test_ndens_state_He_I_rejects_unknown_level(self):
        with pytest.raises(ValueError, match="Unknown excited state"):
            C.ndens_state_He_I(5, 1e15, 5000.0)

    def test_simple_hydrogen_bf_is_zero_below_threshold(self):
        from korg.constants import RydbergH_eV, hplanck_eV
        n = 10
        nu_thresh = RydbergH_eV / (n * n) / hplanck_eV
        assert float(C.simple_hydrogen_bf_cross_section(n, nu_thresh * 0.9)) == 0.0
        assert float(C.simple_hydrogen_bf_cross_section(n, nu_thresh * 1.1)) > 0.0

    @pytest.mark.parametrize("name,charge", [
        ("H_I", 0), ("He_II", 1), ("C_III", 2), ("Fe_IV", 3), ("X_V", 4),
        ("Ca_X", 9), ("H", 0), ("weird_ZZ", 0),
    ])
    def test_parse_species_charge(self, name, charge):
        assert C._parse_species_charge(name) == charge


# ===========================================================================
# 3. AUTODIFF
# ===========================================================================

def _central_difference(f, x, rel_step=1e-6):
    h = abs(x) * rel_step
    return (f(x + h) - f(x - h)) / (2 * h)


class TestAutodiff:
    """grad must be finite everywhere, and match finite differences in bounds."""

    SOURCES = {
        "Hminus_bf": lambda nu, T: C.Hminus_bf(nu, T, 1e16, 1e13),
        "Hminus_ff": lambda nu, T: C.Hminus_ff(nu, T, 1e16, 1e13),
        "Heminus_ff": lambda nu, T: C.Heminus_ff(nu, T, 1e15, 1e13),
        "H2plus_bf_and_ff": lambda nu, T: C.H2plus_bf_and_ff(nu, T, 1e17, 1e12),
    }

    @pytest.mark.parametrize("name", sorted(SOURCES))
    def test_grad_matches_finite_difference_in_bounds(self, name):
        f = self.SOURCES[name]
        nu, T = nu_of_A(8000.0), 5778.0

        gT = float(jax.grad(lambda t: f(nu, t))(T))
        fdT = _central_difference(lambda t: float(f(nu, t)), T)
        assert gT == pytest.approx(fdT, rel=1e-5), f"{name}: d/dT"

        gnu = float(jax.grad(lambda n: f(n, T))(nu))
        fdnu = _central_difference(lambda n: float(f(n, T)), nu)
        assert gnu == pytest.approx(fdnu, rel=1e-5), f"{name}: d/dν"

        assert gT != 0.0 and gnu != 0.0, f"{name}: gradient is identically zero"

    @pytest.mark.parametrize("name", sorted(SOURCES))
    @pytest.mark.parametrize("lam,T,label", [
        (8000.0, 12000.0, "T above the table"),
        (8000.0, 500.0, "T below the table"),
        (300000.0, 5778.0, "λ above the table"),
        (100.0, 5778.0, "λ below the table"),
        (8000.0, 0.0, "T = 0 (degenerate)"),
    ])
    def test_grad_is_finite_out_of_bounds(self, name, lam, T, label):
        """A masked branch must not leak a NaN cotangent.

        ``jnp.where(mask, value, 0.0)`` hides a NaN *value* but reverse mode still
        multiplies the discarded branch's derivative by zero — and 0 * NaN is NaN.
        The fix is ``clamp_to_bound``, which folds out-of-bounds inputs onto a
        strictly positive stand-in before any log/sqrt/division.
        """
        f = self.SOURCES[name]
        nu = nu_of_A(lam)
        gT = float(jax.grad(lambda t: f(nu, t))(T))
        gnu = float(jax.grad(lambda n: f(n, T))(nu))
        assert np.isfinite(gT), f"{name} @ {label}: d/dT = {gT}"
        assert np.isfinite(gnu), f"{name} @ {label}: d/dν = {gnu}"

    def test_grad_wrt_densities_is_exact(self):
        """All four sources are linear in their density arguments."""
        nu, T = nu_of_A(8000.0), 5778.0
        g = float(jax.grad(lambda n: C.Hminus_ff(nu, T, n, 1e13))(1e16))
        assert g == pytest.approx(float(C.Hminus_ff(nu, T, 1.0, 1e13)), rel=1e-12)
        g = float(jax.grad(lambda n: C.Heminus_ff(nu, T, 1e15, n))(1e13))
        assert g == pytest.approx(float(C.Heminus_ff(nu, T, 1e15, 1.0)), rel=1e-12)

    def test_grad_of_total_continuum_is_finite(self, julia_ref):
        if "continuum_sources" not in julia_ref:
            pytest.skip("continuum_sources fixture missing")
        block = julia_ref["continuum_sources"]["solar"]
        from korg.species import Species
        nd = {Species(k.replace("_", " ")): v
              for k, v in block["number_densities"].items()}
        pf = {"H_I": lambda x: block["U_H_I"], "He_I": lambda x: block["U_He_I"]}
        nu = jnp.array([nu_of_A(5000.0), nu_of_A(8000.0)])

        def total(T):
            return jnp.sum(C.total_continuum_absorption(nu, T, block["ne"], nd, pf))

        g = float(jax.grad(total)(block["T"]))
        assert np.isfinite(g) and g != 0.0

    def test_electron_scattering_grad(self):
        g = float(jax.grad(C.electron_scattering)(1e13))
        assert g == pytest.approx(float(C.electron_scattering(1.0)), rel=1e-13)

    def test_rayleigh_grad_is_finite(self):
        g = jax.grad(lambda nu: C.rayleigh(nu, 1e17, 1e16, 1e12))(nu_of_A(5000.0))
        assert np.isfinite(float(g)) and float(g) != 0.0


# ===========================================================================
# 4. JIT TRACING
# ===========================================================================

class TestJitTracing:

    @pytest.mark.parametrize("name,fn", [
        ("Hminus_bf", lambda nu, T: C.Hminus_bf(nu, T, 1e16, 1e13)),
        ("Hminus_ff", lambda nu, T: C.Hminus_ff(nu, T, 1e16, 1e13)),
        ("Heminus_ff", lambda nu, T: C.Heminus_ff(nu, T, 1e15, 1e13)),
        ("H2plus_bf_and_ff", lambda nu, T: C.H2plus_bf_and_ff(nu, T, 1e17, 1e12)),
        ("_H2plus_bf_and_ff", lambda nu, T: C._H2plus_bf_and_ff(nu, T, 1e17, 1e12)),
    ])
    def test_sources_jit(self, name, fn):
        jitted = jax.jit(fn)
        nu, T = nu_of_A(8000.0), 5778.0
        assert float(jitted(nu, T)) == pytest.approx(float(fn(nu, T)), rel=1e-14)

    @pytest.mark.parametrize("T", [500.0, 5778.0, 12000.0])
    def test_bounds_are_applied_under_jit(self, T):
        """The mask is data-dependent, so it must survive tracing."""
        f = jax.jit(lambda nu, t: C.Hminus_ff(nu, t, 1e16, 1e13))
        nu = nu_of_A(8000.0)
        assert float(f(nu, T)) == pytest.approx(
            float(C.Hminus_ff(nu, T, 1e16, 1e13)), rel=1e-14)

    def test_vmap_over_frequency_and_temperature(self):
        nus = jnp.array([nu_of_A(l) for l in (3000.0, 8000.0, 200000.0)])
        Ts = jnp.array([500.0, 5778.0, 12000.0])
        f = jax.jit(jax.vmap(jax.vmap(lambda nu, T: C.Hminus_ff(nu, T, 1e16, 1e13),
                                      in_axes=(0, None)),
                             in_axes=(None, 0)))
        out = np.asarray(f(nus, Ts))
        assert out.shape == (3, 3)
        assert np.all(np.isfinite(out))
        assert np.all(out[0] == 0.0) and np.all(out[2] == 0.0)   # T out of bounds
        assert out[1, 2] == 0.0                                   # λ out of bounds
        assert out[1, 1] > 0.0

    def test_array_input_is_masked_elementwise(self):
        nus = jnp.array([nu_of_A(200000.0), nu_of_A(8000.0), nu_of_A(100.0)])
        out = np.asarray(C.Hminus_ff(nus, 5000.0, 1e16, 1e13))
        assert out[0] == 0.0 and out[2] == 0.0 and out[1] > 0.0

    def test_bounds_checked_absorption_cannot_be_jitted(self):
        """The NumPy wrapper computes ``func`` only on the in-bounds slice, whose
        extent depends on the *values* of ``nus``.  Array shapes cannot depend on
        a traced value, so this provably cannot trace — use ``in_bounds_mask``.
        """
        f = bounds_checked_absorption(_kernel, nu_bound=closed_interval(10.0, 100.0))
        with pytest.raises(jax.errors.TracerArrayConversionError):
            jax.jit(lambda nus: f(nus, 1500.0))(jnp.array([20.0, 50.0]))

    def test_contained_slice_cannot_be_traced(self):
        """np.searchsorted on a tracer is not traceable — by design."""
        with pytest.raises(jax.errors.TracerArrayConversionError):
            jax.jit(lambda v: float(contained_slice(v, closed_interval(1.0, 2.0)).stop))(
                jnp.array([0.5, 1.5, 2.5]))


# ===========================================================================
# Regression: adopting the bounds must not move any in-atmosphere result
# ===========================================================================

class TestNoRegressionInsideTheAtmosphere:

    def test_solar_model_never_leaves_any_bound(self):
        """Justifies adopting Julia's bounds: for sun.mod every layer is inside
        every table, so no synthesis result can change.

        Reads ``tests/data/sun.mod``, the tracked copy that every other test uses.
        This pointed at ``<repo root>/sun.mod`` — an *untracked* file that happens
        to exist in this working tree — behind a ``pytest.skip`` if it was absent.
        On a fresh clone the test would have skipped silently, taking with it the
        entire regression argument for adopting Korg.jl's bounds. No skip now: the
        file is tracked, so a missing one is a real failure.
        """
        from korg.atmosphere import read_model_atmosphere
        path = os.path.join(os.path.dirname(__file__), "data", "sun.mod")
        T = np.array([l.temperature for l in read_model_atmosphere(path).layers])
        assert T.min() > HMINUS_FF_TEMP_BOUND.lower
        assert T.max() < HMINUS_FF_TEMP_BOUND.upper
        assert T.min() > H2PLUS_TEMP_BOUND.lower
        assert T.max() < H2PLUS_TEMP_BOUND.upper

    def test_solar_continuum_sources_still_match_julia(self, julia_ref):
        """The pre-existing per-source fixtures, re-asserted at rtol 1e-13."""
        if "continuum_sources" not in julia_ref:
            pytest.skip("continuum_sources fixture missing")
        for label, block in julia_ref["continuum_sources"].items():
            T, ne = block["T"], block["ne"]
            for wl_str, ref in block["outputs"]["Hminus_ff"].items():
                got = float(C.Hminus_ff(nu_of_A(float(wl_str)), T,
                                        block["nH_I_div_U"], ne))
                assert got == pytest.approx(ref, rel=1e-13, abs=0.0), \
                    f"{label} Hminus_ff @ {wl_str} A"
            for wl_str, ref in block["outputs"]["Heminus_ff"].items():
                got = float(C.Heminus_ff(nu_of_A(float(wl_str)), T,
                                         block["nHe_I_div_U"], ne))
                if ref == 0.0:
                    assert got == 0.0, f"{label} Heminus_ff @ {wl_str} A"
                else:
                    assert got == pytest.approx(ref, rel=1e-13, abs=0.0), \
                        f"{label} Heminus_ff @ {wl_str} A"


# ===========================================================================
# Duplicate implementations: pinned, not silently reconciled
# ===========================================================================

class TestHminusBfDataLoadingFailure:
    """The two error paths taken when the McLaughlin+ 2017 data file is absent.

    Both are defensive and neither runs in a working install, so they were the
    last uncovered statements in ``absorption_h_minus.py``.  They are worth
    exercising rather than excluding: the ``except FileNotFoundError: pass`` in
    the initializer is what turns a missing data file into a *deferred* failure,
    and the ``raise`` in the cross-section is what makes that failure legible
    instead of a confusing ``None`` dereference.
    """

    def test_initializer_swallows_a_missing_data_file(self, monkeypatch):
        import korg.continuum_absorption.absorption_h_minus as m

        def boom(fname=None):
            raise FileNotFoundError("no such file")

        monkeypatch.setattr(m, "_HMINUS_BF_NU", None)
        monkeypatch.setattr(m, "_HMINUS_BF_SIGMA", None)
        monkeypatch.setattr(m, "_HMINUS_BF_MIN_NU", None)
        monkeypatch.setattr(m, "_load_Hminus_bf_data", boom)
        m._initialize_Hminus_bf_jax_data()          # must not propagate
        assert m._HMINUS_BF_NU is None

    def test_cross_section_raises_when_data_never_loaded(self, monkeypatch):
        import korg.continuum_absorption.absorption_h_minus as m

        def boom(fname=None):
            raise FileNotFoundError("no such file")

        monkeypatch.setattr(m, "_HMINUS_BF_NU", None)
        monkeypatch.setattr(m, "_load_Hminus_bf_data", boom)
        with pytest.raises(FileNotFoundError, match="bound-free data file"):
            m._Hminus_bf_cross_section(nu_of_A(5000.0))

    def test_initializer_is_a_no_op_once_loaded(self):
        """The early return: a second call must not re-read the file."""
        import korg.continuum_absorption.absorption_h_minus as m
        m._initialize_Hminus_bf_jax_data()
        assert m._HMINUS_BF_NU is not None
        before = m._HMINUS_BF_NU
        m._initialize_Hminus_bf_jax_data()
        assert m._HMINUS_BF_NU is before


class TestDuplicateImplementations:
    """korg.continuum and korg.continuum_absorption.* carry parallel copies.

    These tests record how they differ so nobody assumes they are interchangeable.
    Reconciling them is a separate decision.
    """

    @pytest.mark.parametrize("lam", [3000.0, 5000.0, 8000.0, 10000.0, 20000.0])
    def test_hminus_ff_duplicates_now_agree_exactly(self, lam):
        """``absorption_h_minus.Hminus_ff`` forwards to the corrected implementation.

        It used to interpolate the (non-uniform) Bell & Berrington grid with
        uniform-grid index arithmetic and was wrong by 1.26× at 3000 Å rising to
        69× at 20000 Å.
        """
        from korg.continuum_absorption.absorption_h_minus import Hminus_ff as ff_alt
        nu, T = nu_of_A(lam), 5778.0
        assert float(ff_alt(nu, T, 1e16, 1e13)) == float(C.Hminus_ff(nu, T, 1e16, 1e13))

    @pytest.mark.parametrize("lam", [8000.0, 10000.0, 20000.0])
    def test_heminus_ff_duplicates_now_agree_exactly(self, lam):
        """Same defect in the John (1994) table: 2.0× at 8000 Å, 65× at 20000 Å."""
        from korg.continuum_absorption.absorption_He import Heminus_ff as he_alt
        nu, T = nu_of_A(lam), 5778.0
        assert float(he_alt(nu, T, 1e15, 1e13)) == float(C.Heminus_ff(nu, T, 1e15, 1e13))

    def test_the_uniform_grid_interpolator_is_gone(self):
        """The defective kernels are deleted, not kept as documentation.

        ``_bilinear_interp_jax`` indexed with ``(x - x0)/(x1 - x0)``, which is only
        correct for a uniformly spaced grid; neither table axis is uniform, and the
        error reached 68x at 20000 AA.  An earlier revision kept the private kernels
        so the divergence stayed inspectable, but a wrong private function is
        reachable by the next person who goes looking for one -- the record belongs
        in the docstrings and the git history, not in importable code.
        """
        import korg.continuum_absorption.absorption_He as He
        import korg.continuum_absorption.absorption_h_minus as Hm
        for mod in (He, Hm):
            assert not hasattr(mod, "_bilinear_interp_jax"), mod.__name__
        assert not hasattr(He, "_Heminus_ff")
        assert not hasattr(Hm, "_HMINUS_FF_TABLE")

    def test_hminus_ff_duplicates_agree_out_of_bounds(self):
        from korg.continuum_absorption.absorption_h_minus import Hminus_ff as ff_alt
        nu, T = nu_of_A(8000.0), 12000.0
        assert float(C.Hminus_ff(nu, T, 1e16, 1e13)) == 0.0
        assert float(ff_alt(nu, T, 1e16, 1e13)) == 0.0

    def test_hminus_ff_jax_is_now_an_alias(self):
        """It used to be a byte-identical copy over duplicated tables."""
        from korg.continuum_absorption.absorption_h_minus import (
            Hminus_ff as ff, Hminus_ff_jax as ff_jax)
        nu, T = nu_of_A(8000.0), 5778.0
        assert float(ff_jax(nu, T, 1e16, 1e13)) == float(ff(nu, T, 1e16, 1e13))

    def test_hminus_bf_duplicates_agree(self):
        from korg.continuum_absorption.absorption_h_minus import (
            _Hminus_bf_cross_section)
        for lam in (3000.0, 8000.0, 16000.0, 20000.0):
            nu = nu_of_A(lam)
            assert float(_Hminus_bf_cross_section(nu)) == pytest.approx(
                float(C.Hminus_bf_cross_section(nu)), rel=1e-12, abs=1e-30)

    def test_hminus_bf_cross_section_grad_is_finite_below_threshold(self):
        """``(ν − ν_ion)**1.5`` is NaN below the detachment threshold; the
        ``jnp.where`` masks the value but not the cotangent.  Both copies are
        guarded with a strictly positive stand-in."""
        from korg.continuum_absorption.absorption_h_minus import (
            _Hminus_bf_cross_section)
        for fn in (C.Hminus_bf_cross_section, _Hminus_bf_cross_section):
            for nu in (C._Hminus_ion_nu * 0.5, C._Hminus_ion_nu, nu_of_A(300000.0)):
                g = float(jax.grad(lambda x: jnp.sum(fn(x)))(nu))
                assert np.isfinite(g), f"{fn.__name__} at nu={nu}"

    def test_ndens_state_He_I_duplicates_agree(self):
        from korg.continuum_absorption.absorption_He import (
            ndens_state_He_I as he_alt)
        for n in (1, 2, 3, 4):
            assert float(he_alt(n, 1e15, 5000.0)) == pytest.approx(
                float(C.ndens_state_He_I(n, 1e15, 5000.0)), rel=1e-14)
        with pytest.raises(ValueError, match="Unknown excited state"):
            he_alt(5, 1e15, 5000.0)

    def test_ndens_Hminus_duplicates_agree_to_roundoff(self):
        """Both derive the Saha coefficient from korg.constants rather than
        carrying Korg v1.1's literal 3.31283018e-22 (high by 9.2e-7).

        This asserted bitwise equality, which holds on the CPU backend but not
        on the GPU one: the two copies write the same quantity as differently
        associated products, and XLA is free to contract them differently, so at
        T = 9000 K they land one ulp apart (64132966.8649147 vs
        ...86491471).  A 9.2e-7 discrepancy is what this test exists to catch;
        1e-15 separates that cleanly from backend rounding.
        """
        from korg.continuum_absorption.absorption_h_minus import _ndens_Hminus
        for T in (3500.0, 5778.0, 9000.0):
            assert float(_ndens_Hminus(1e16, 1e13, T)) == pytest.approx(
                float(C.ndens_Hminus(1e16, 1e13, T)), rel=1e-15)

    def test_saha_coefficient_matches_its_derivation(self):
        """Guard against the literal creeping back in."""
        from korg.constants import (hplanck_cgs, kboltz_eV, kboltz_cgs,
                                    electron_mass_cgs)
        derived = (hplanck_cgs ** 2 * kboltz_eV
                   / (2 * np.pi * electron_mass_cgs * kboltz_cgs)) ** 1.5
        stale_literal = 3.31283018e-22
        # ndens_Hminus == 0.25 * (2 * nHI) * ne * coef * beta^1.5 * exp(chi*beta)
        T, nHI, ne = 5778.0, 1.0, 1.0
        beta = 1.0 / (kboltz_eV * T)
        expected = (0.25 * 2 * nHI * ne * derived * beta ** 1.5
                    * np.exp(0.754204 * beta))
        assert float(C.ndens_Hminus(nHI, ne, T)) == pytest.approx(expected, rel=1e-15)
        assert derived != stale_literal
        assert abs(stale_literal / derived - 1.0) == pytest.approx(9.2e-7, rel=0.1)
